
namespace InterfaceErgonomico
{
    partial class LoginForm
    {
        /// <summary>
        /// Variável de designer necessária.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Limpar os recursos que estão sendo usados.
        /// </summary>
        /// <param name="disposing">true se for necessário descartar os recursos gerenciados; caso contrário, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Código gerado pelo Windows Form Designer

        /// <summary>
        /// Método necessário para suporte ao Designer - não modifique 
        /// o conteúdo deste método com o editor de código.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(LoginForm));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.bunifuImageButton1 = new Bunifu.UI.WinForms.BunifuImageButton();
            this.MinimizeBtn = new Bunifu.UI.WinForms.BunifuImageButton();
            this.PasswordCheckBtn = new Bunifu.UI.WinForms.BunifuCheckBox();
            this.UsernameTextBtn = new Bunifu.UI.WinForms.BunifuTextBox();
            this.PasswordBtn = new Bunifu.UI.WinForms.BunifuTextBox();
            this.LoginBtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.pictureBox1 = new System.Windows.Forms.PictureBox();
            this.MoreText = new Bunifu.UI.WinForms.BunifuLabel();
            this.ShowPasswordBtn = new Bunifu.UI.WinForms.BunifuCheckBox();
            this.ShowPasswordText = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuPanel1 = new Bunifu.UI.WinForms.BunifuPanel();
            this.MostrarRegisterText = new Bunifu.UI.WinForms.BunifuLabel();
            this.MostrarRegister = new Bunifu.UI.WinForms.BunifuCheckBox();
            this.ReturnBtn = new Bunifu.UI.WinForms.BunifuImageButton();
            this.ConfirmButton = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.SenhaRegisterTxt = new Bunifu.UI.WinForms.BunifuLabel();
            this.UsuarioRegisterTxt = new Bunifu.UI.WinForms.BunifuLabel();
            this.DtaNascimentoRegisterTxt = new Bunifu.UI.WinForms.BunifuLabel();
            this.SobrenomeRegisterTxt = new Bunifu.UI.WinForms.BunifuLabel();
            this.NameRegisterTxt = new Bunifu.UI.WinForms.BunifuLabel();
            this.DtaNascimento = new Bunifu.UI.WinForms.BunifuDatePicker();
            this.PasswordText = new Bunifu.UI.WinForms.BunifuTextBox();
            this.UsuarioBtn = new Bunifu.UI.WinForms.BunifuTextBox();
            this.SobrenomeText = new Bunifu.UI.WinForms.BunifuTextBox();
            this.NameText = new Bunifu.UI.WinForms.BunifuTextBox();
            this.ConnectionStatus = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel2 = new Bunifu.UI.WinForms.BunifuLabel();
            this.RegisterBtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).BeginInit();
            this.bunifuPanel1.SuspendLayout();
            this.SuspendLayout();
            // 
            // bunifuImageButton1
            // 
            this.bunifuImageButton1.ActiveImage = null;
            this.bunifuImageButton1.AllowAnimations = true;
            this.bunifuImageButton1.AllowBuffering = false;
            this.bunifuImageButton1.AllowToggling = false;
            this.bunifuImageButton1.AllowZooming = true;
            this.bunifuImageButton1.AllowZoomingOnFocus = false;
            this.bunifuImageButton1.BackColor = System.Drawing.Color.Transparent;
            this.bunifuImageButton1.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuImageButton1.ErrorImage = ((System.Drawing.Image)(resources.GetObject("bunifuImageButton1.ErrorImage")));
            this.bunifuImageButton1.FadeWhenInactive = false;
            this.bunifuImageButton1.Flip = Bunifu.UI.WinForms.BunifuImageButton.FlipOrientation.Normal;
            this.bunifuImageButton1.ForeColor = System.Drawing.SystemColors.ActiveBorder;
            this.bunifuImageButton1.Image = ((System.Drawing.Image)(resources.GetObject("bunifuImageButton1.Image")));
            this.bunifuImageButton1.ImageActive = null;
            this.bunifuImageButton1.ImageLocation = null;
            this.bunifuImageButton1.ImageMargin = 0;
            this.bunifuImageButton1.ImageSize = new System.Drawing.Size(31, 28);
            this.bunifuImageButton1.ImageZoomSize = new System.Drawing.Size(32, 29);
            this.bunifuImageButton1.InitialImage = ((System.Drawing.Image)(resources.GetObject("bunifuImageButton1.InitialImage")));
            this.bunifuImageButton1.Location = new System.Drawing.Point(639, 12);
            this.bunifuImageButton1.Name = "bunifuImageButton1";
            this.bunifuImageButton1.Rotation = 0;
            this.bunifuImageButton1.ShowActiveImage = true;
            this.bunifuImageButton1.ShowCursorChanges = true;
            this.bunifuImageButton1.ShowImageBorders = true;
            this.bunifuImageButton1.ShowSizeMarkers = false;
            this.bunifuImageButton1.Size = new System.Drawing.Size(32, 29);
            this.bunifuImageButton1.TabIndex = 2;
            this.bunifuImageButton1.ToolTipText = "";
            this.bunifuImageButton1.WaitOnLoad = false;
            this.bunifuImageButton1.Zoom = 0;
            this.bunifuImageButton1.ZoomSpeed = 10;
            this.bunifuImageButton1.Click += new System.EventHandler(this.bunifuImageButton1_Click);
            // 
            // MinimizeBtn
            // 
            this.MinimizeBtn.ActiveImage = null;
            this.MinimizeBtn.AllowAnimations = true;
            this.MinimizeBtn.AllowBuffering = false;
            this.MinimizeBtn.AllowToggling = false;
            this.MinimizeBtn.AllowZooming = true;
            this.MinimizeBtn.AllowZoomingOnFocus = false;
            this.MinimizeBtn.BackColor = System.Drawing.Color.Transparent;
            this.MinimizeBtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.MinimizeBtn.ErrorImage = ((System.Drawing.Image)(resources.GetObject("MinimizeBtn.ErrorImage")));
            this.MinimizeBtn.FadeWhenInactive = false;
            this.MinimizeBtn.Flip = Bunifu.UI.WinForms.BunifuImageButton.FlipOrientation.Normal;
            this.MinimizeBtn.ForeColor = System.Drawing.SystemColors.ActiveBorder;
            this.MinimizeBtn.Image = ((System.Drawing.Image)(resources.GetObject("MinimizeBtn.Image")));
            this.MinimizeBtn.ImageActive = null;
            this.MinimizeBtn.ImageLocation = null;
            this.MinimizeBtn.ImageMargin = 0;
            this.MinimizeBtn.ImageSize = new System.Drawing.Size(31, 28);
            this.MinimizeBtn.ImageZoomSize = new System.Drawing.Size(32, 29);
            this.MinimizeBtn.InitialImage = ((System.Drawing.Image)(resources.GetObject("MinimizeBtn.InitialImage")));
            this.MinimizeBtn.Location = new System.Drawing.Point(601, 12);
            this.MinimizeBtn.Name = "MinimizeBtn";
            this.MinimizeBtn.Rotation = 0;
            this.MinimizeBtn.ShowActiveImage = true;
            this.MinimizeBtn.ShowCursorChanges = true;
            this.MinimizeBtn.ShowImageBorders = true;
            this.MinimizeBtn.ShowSizeMarkers = false;
            this.MinimizeBtn.Size = new System.Drawing.Size(32, 29);
            this.MinimizeBtn.TabIndex = 6;
            this.MinimizeBtn.ToolTipText = "";
            this.MinimizeBtn.WaitOnLoad = false;
            this.MinimizeBtn.Zoom = 0;
            this.MinimizeBtn.ZoomSpeed = 10;
            this.MinimizeBtn.Click += new System.EventHandler(this.MinimizeBtn_Click);
            // 
            // PasswordCheckBtn
            // 
            this.PasswordCheckBtn.AllowBindingControlAnimation = true;
            this.PasswordCheckBtn.AllowBindingControlColorChanges = false;
            this.PasswordCheckBtn.AllowBindingControlLocation = true;
            this.PasswordCheckBtn.AllowCheckBoxAnimation = false;
            this.PasswordCheckBtn.AllowCheckmarkAnimation = true;
            this.PasswordCheckBtn.AllowOnHoverStates = true;
            this.PasswordCheckBtn.AutoCheck = true;
            this.PasswordCheckBtn.BackColor = System.Drawing.Color.Transparent;
            this.PasswordCheckBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("PasswordCheckBtn.BackgroundImage")));
            this.PasswordCheckBtn.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Zoom;
            this.PasswordCheckBtn.BindingControlPosition = Bunifu.UI.WinForms.BunifuCheckBox.BindingControlPositions.Right;
            this.PasswordCheckBtn.BorderRadius = 12;
            this.PasswordCheckBtn.Checked = true;
            this.PasswordCheckBtn.CheckState = Bunifu.UI.WinForms.BunifuCheckBox.CheckStates.Checked;
            this.PasswordCheckBtn.Cursor = System.Windows.Forms.Cursors.Default;
            this.PasswordCheckBtn.CustomCheckmarkImage = null;
            this.PasswordCheckBtn.Location = new System.Drawing.Point(206, 120);
            this.PasswordCheckBtn.MinimumSize = new System.Drawing.Size(17, 17);
            this.PasswordCheckBtn.Name = "PasswordCheckBtn";
            this.PasswordCheckBtn.OnCheck.BorderColor = System.Drawing.Color.SlateBlue;
            this.PasswordCheckBtn.OnCheck.BorderRadius = 12;
            this.PasswordCheckBtn.OnCheck.BorderThickness = 2;
            this.PasswordCheckBtn.OnCheck.CheckBoxColor = System.Drawing.Color.DarkSlateBlue;
            this.PasswordCheckBtn.OnCheck.CheckmarkColor = System.Drawing.Color.White;
            this.PasswordCheckBtn.OnCheck.CheckmarkThickness = 2;
            this.PasswordCheckBtn.OnDisable.BorderColor = System.Drawing.Color.LightGray;
            this.PasswordCheckBtn.OnDisable.BorderRadius = 12;
            this.PasswordCheckBtn.OnDisable.BorderThickness = 2;
            this.PasswordCheckBtn.OnDisable.CheckBoxColor = System.Drawing.Color.Transparent;
            this.PasswordCheckBtn.OnDisable.CheckmarkColor = System.Drawing.Color.LightGray;
            this.PasswordCheckBtn.OnDisable.CheckmarkThickness = 2;
            this.PasswordCheckBtn.OnHoverChecked.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.PasswordCheckBtn.OnHoverChecked.BorderRadius = 12;
            this.PasswordCheckBtn.OnHoverChecked.BorderThickness = 2;
            this.PasswordCheckBtn.OnHoverChecked.CheckBoxColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.PasswordCheckBtn.OnHoverChecked.CheckmarkColor = System.Drawing.Color.White;
            this.PasswordCheckBtn.OnHoverChecked.CheckmarkThickness = 2;
            this.PasswordCheckBtn.OnHoverUnchecked.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.PasswordCheckBtn.OnHoverUnchecked.BorderRadius = 12;
            this.PasswordCheckBtn.OnHoverUnchecked.BorderThickness = 1;
            this.PasswordCheckBtn.OnHoverUnchecked.CheckBoxColor = System.Drawing.Color.Transparent;
            this.PasswordCheckBtn.OnUncheck.BorderColor = System.Drawing.Color.DarkGray;
            this.PasswordCheckBtn.OnUncheck.BorderRadius = 12;
            this.PasswordCheckBtn.OnUncheck.BorderThickness = 1;
            this.PasswordCheckBtn.OnUncheck.CheckBoxColor = System.Drawing.Color.Transparent;
            this.PasswordCheckBtn.Size = new System.Drawing.Size(21, 21);
            this.PasswordCheckBtn.Style = Bunifu.UI.WinForms.BunifuCheckBox.CheckBoxStyles.Bunifu;
            this.PasswordCheckBtn.TabIndex = 7;
            this.PasswordCheckBtn.ThreeState = false;
            this.PasswordCheckBtn.ToolTipText = null;
            this.PasswordCheckBtn.CheckedChanged += new System.EventHandler<Bunifu.UI.WinForms.BunifuCheckBox.CheckedChangedEventArgs>(this.PasswordCheck_CheckedChanged);
            // 
            // UsernameTextBtn
            // 
            this.UsernameTextBtn.AcceptsReturn = false;
            this.UsernameTextBtn.AcceptsTab = false;
            this.UsernameTextBtn.AnimationSpeed = 200;
            this.UsernameTextBtn.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.UsernameTextBtn.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.UsernameTextBtn.BackColor = System.Drawing.Color.Transparent;
            this.UsernameTextBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("UsernameTextBtn.BackgroundImage")));
            this.UsernameTextBtn.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.UsernameTextBtn.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.UsernameTextBtn.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.UsernameTextBtn.BorderColorIdle = System.Drawing.Color.White;
            this.UsernameTextBtn.BorderRadius = 1;
            this.UsernameTextBtn.BorderThickness = 1;
            this.UsernameTextBtn.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.UsernameTextBtn.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.UsernameTextBtn.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.UsernameTextBtn.DefaultText = "";
            this.UsernameTextBtn.FillColor = System.Drawing.Color.White;
            this.UsernameTextBtn.ForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            this.UsernameTextBtn.HideSelection = true;
            this.UsernameTextBtn.IconLeft = null;
            this.UsernameTextBtn.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.UsernameTextBtn.IconPadding = 10;
            this.UsernameTextBtn.IconRight = null;
            this.UsernameTextBtn.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.UsernameTextBtn.Lines = new string[0];
            this.UsernameTextBtn.Location = new System.Drawing.Point(206, 17);
            this.UsernameTextBtn.MaxLength = 32767;
            this.UsernameTextBtn.MinimumSize = new System.Drawing.Size(1, 1);
            this.UsernameTextBtn.Modified = false;
            this.UsernameTextBtn.Multiline = false;
            this.UsernameTextBtn.Name = "UsernameTextBtn";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.UsernameTextBtn.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(192)))), ((int)(((byte)(192)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.UsernameTextBtn.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.UsernameTextBtn.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.White;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.UsernameTextBtn.OnIdleState = stateProperties4;
            this.UsernameTextBtn.Padding = new System.Windows.Forms.Padding(3);
            this.UsernameTextBtn.PasswordChar = '\0';
            this.UsernameTextBtn.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.UsernameTextBtn.PlaceholderText = "Usuário";
            this.UsernameTextBtn.ReadOnly = false;
            this.UsernameTextBtn.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.UsernameTextBtn.SelectedText = "";
            this.UsernameTextBtn.SelectionLength = 0;
            this.UsernameTextBtn.SelectionStart = 0;
            this.UsernameTextBtn.ShortcutsEnabled = true;
            this.UsernameTextBtn.Size = new System.Drawing.Size(260, 37);
            this.UsernameTextBtn.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.UsernameTextBtn.TabIndex = 8;
            this.UsernameTextBtn.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.UsernameTextBtn.TextMarginBottom = 0;
            this.UsernameTextBtn.TextMarginLeft = 3;
            this.UsernameTextBtn.TextMarginTop = 0;
            this.UsernameTextBtn.TextPlaceholder = "Usuário";
            this.UsernameTextBtn.UseSystemPasswordChar = false;
            this.UsernameTextBtn.WordWrap = true;
            this.UsernameTextBtn.KeyPress += new System.Windows.Forms.KeyPressEventHandler(this.UsernameTextBtn_KeyPress);
            // 
            // PasswordBtn
            // 
            this.PasswordBtn.AcceptsReturn = false;
            this.PasswordBtn.AcceptsTab = false;
            this.PasswordBtn.AnimationSpeed = 200;
            this.PasswordBtn.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.PasswordBtn.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.PasswordBtn.BackColor = System.Drawing.Color.Transparent;
            this.PasswordBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("PasswordBtn.BackgroundImage")));
            this.PasswordBtn.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.PasswordBtn.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.PasswordBtn.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.PasswordBtn.BorderColorIdle = System.Drawing.Color.White;
            this.PasswordBtn.BorderRadius = 1;
            this.PasswordBtn.BorderThickness = 1;
            this.PasswordBtn.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.PasswordBtn.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.PasswordBtn.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.PasswordBtn.DefaultText = "";
            this.PasswordBtn.FillColor = System.Drawing.Color.White;
            this.PasswordBtn.ForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            this.PasswordBtn.HideSelection = true;
            this.PasswordBtn.IconLeft = null;
            this.PasswordBtn.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.PasswordBtn.IconPadding = 10;
            this.PasswordBtn.IconRight = null;
            this.PasswordBtn.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.PasswordBtn.Lines = new string[0];
            this.PasswordBtn.Location = new System.Drawing.Point(206, 77);
            this.PasswordBtn.MaxLength = 32767;
            this.PasswordBtn.MinimumSize = new System.Drawing.Size(1, 1);
            this.PasswordBtn.Modified = false;
            this.PasswordBtn.Multiline = false;
            this.PasswordBtn.Name = "PasswordBtn";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.PasswordBtn.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.PasswordBtn.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.PasswordBtn.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.White;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.PasswordBtn.OnIdleState = stateProperties8;
            this.PasswordBtn.Padding = new System.Windows.Forms.Padding(3);
            this.PasswordBtn.PasswordChar = '●';
            this.PasswordBtn.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.PasswordBtn.PlaceholderText = "Senha";
            this.PasswordBtn.ReadOnly = false;
            this.PasswordBtn.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.PasswordBtn.SelectedText = "";
            this.PasswordBtn.SelectionLength = 0;
            this.PasswordBtn.SelectionStart = 0;
            this.PasswordBtn.ShortcutsEnabled = true;
            this.PasswordBtn.Size = new System.Drawing.Size(260, 37);
            this.PasswordBtn.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.PasswordBtn.TabIndex = 9;
            this.PasswordBtn.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.PasswordBtn.TextMarginBottom = 0;
            this.PasswordBtn.TextMarginLeft = 3;
            this.PasswordBtn.TextMarginTop = 0;
            this.PasswordBtn.TextPlaceholder = "Senha";
            this.PasswordBtn.UseSystemPasswordChar = false;
            this.PasswordBtn.WordWrap = true;
            this.PasswordBtn.TextChanged += new System.EventHandler(this.PasswordText_TextChanged);
            // 
            // LoginBtn
            // 
            this.LoginBtn.AllowAnimations = true;
            this.LoginBtn.AllowMouseEffects = true;
            this.LoginBtn.AllowToggling = false;
            this.LoginBtn.AnimationSpeed = 200;
            this.LoginBtn.AutoGenerateColors = false;
            this.LoginBtn.AutoRoundBorders = false;
            this.LoginBtn.AutoSizeLeftIcon = true;
            this.LoginBtn.AutoSizeRightIcon = true;
            this.LoginBtn.BackColor = System.Drawing.Color.Transparent;
            this.LoginBtn.BackColor1 = System.Drawing.Color.DarkSlateBlue;
            this.LoginBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("LoginBtn.BackgroundImage")));
            this.LoginBtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.LoginBtn.ButtonText = "Entrar";
            this.LoginBtn.ButtonTextMarginLeft = 0;
            this.LoginBtn.ColorContrastOnClick = 45;
            this.LoginBtn.ColorContrastOnHover = 45;
            this.LoginBtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.LoginBtn.CustomizableEdges = borderEdges1;
            this.LoginBtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.LoginBtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.LoginBtn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.LoginBtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.LoginBtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.LoginBtn.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.LoginBtn.ForeColor = System.Drawing.Color.White;
            this.LoginBtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.LoginBtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.LoginBtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.LoginBtn.IconMarginLeft = 11;
            this.LoginBtn.IconPadding = 10;
            this.LoginBtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.LoginBtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.LoginBtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.LoginBtn.IconSize = 25;
            this.LoginBtn.IdleBorderColor = System.Drawing.Color.Silver;
            this.LoginBtn.IdleBorderRadius = 1;
            this.LoginBtn.IdleBorderThickness = 1;
            this.LoginBtn.IdleFillColor = System.Drawing.Color.DarkSlateBlue;
            this.LoginBtn.IdleIconLeftImage = null;
            this.LoginBtn.IdleIconRightImage = null;
            this.LoginBtn.IndicateFocus = false;
            this.LoginBtn.Location = new System.Drawing.Point(206, 147);
            this.LoginBtn.Name = "LoginBtn";
            this.LoginBtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.LoginBtn.OnDisabledState.BorderRadius = 1;
            this.LoginBtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.LoginBtn.OnDisabledState.BorderThickness = 1;
            this.LoginBtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.LoginBtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.LoginBtn.OnDisabledState.IconLeftImage = null;
            this.LoginBtn.OnDisabledState.IconRightImage = null;
            this.LoginBtn.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(37)))), ((int)(((byte)(39)))), ((int)(((byte)(56)))));
            this.LoginBtn.onHoverState.BorderRadius = 1;
            this.LoginBtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.LoginBtn.onHoverState.BorderThickness = 1;
            this.LoginBtn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(37)))), ((int)(((byte)(39)))), ((int)(((byte)(56)))));
            this.LoginBtn.onHoverState.ForeColor = System.Drawing.Color.White;
            this.LoginBtn.onHoverState.IconLeftImage = null;
            this.LoginBtn.onHoverState.IconRightImage = null;
            this.LoginBtn.OnIdleState.BorderColor = System.Drawing.Color.Silver;
            this.LoginBtn.OnIdleState.BorderRadius = 1;
            this.LoginBtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.LoginBtn.OnIdleState.BorderThickness = 1;
            this.LoginBtn.OnIdleState.FillColor = System.Drawing.Color.DarkSlateBlue;
            this.LoginBtn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.LoginBtn.OnIdleState.IconLeftImage = null;
            this.LoginBtn.OnIdleState.IconRightImage = null;
            this.LoginBtn.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(37)))), ((int)(((byte)(39)))), ((int)(((byte)(56)))));
            this.LoginBtn.OnPressedState.BorderRadius = 1;
            this.LoginBtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.LoginBtn.OnPressedState.BorderThickness = 1;
            this.LoginBtn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(37)))), ((int)(((byte)(39)))), ((int)(((byte)(80)))));
            this.LoginBtn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.LoginBtn.OnPressedState.IconLeftImage = null;
            this.LoginBtn.OnPressedState.IconRightImage = null;
            this.LoginBtn.Size = new System.Drawing.Size(123, 39);
            this.LoginBtn.TabIndex = 10;
            this.LoginBtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.LoginBtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.LoginBtn.TextMarginLeft = 0;
            this.LoginBtn.TextPadding = new System.Windows.Forms.Padding(0);
            this.LoginBtn.UseDefaultRadiusAndThickness = true;
            this.LoginBtn.Click += new System.EventHandler(this.LoginBtn_Click);
            // 
            // pictureBox1
            // 
            this.pictureBox1.Image = global::InterfaceErgonomico.Properties.Resources.Logotipo;
            this.pictureBox1.Location = new System.Drawing.Point(170, 12);
            this.pictureBox1.Name = "pictureBox1";
            this.pictureBox1.Size = new System.Drawing.Size(313, 99);
            this.pictureBox1.SizeMode = System.Windows.Forms.PictureBoxSizeMode.StretchImage;
            this.pictureBox1.TabIndex = 11;
            this.pictureBox1.TabStop = false;
            // 
            // MoreText
            // 
            this.MoreText.AllowParentOverrides = false;
            this.MoreText.AutoEllipsis = false;
            this.MoreText.CursorType = null;
            this.MoreText.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.MoreText.ForeColor = System.Drawing.Color.Gray;
            this.MoreText.Location = new System.Drawing.Point(233, 120);
            this.MoreText.Name = "MoreText";
            this.MoreText.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.MoreText.Size = new System.Drawing.Size(104, 21);
            this.MoreText.TabIndex = 12;
            this.MoreText.Text = "Lembrar senha";
            this.MoreText.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.MoreText.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // ShowPasswordBtn
            // 
            this.ShowPasswordBtn.AllowBindingControlAnimation = true;
            this.ShowPasswordBtn.AllowBindingControlColorChanges = false;
            this.ShowPasswordBtn.AllowBindingControlLocation = true;
            this.ShowPasswordBtn.AllowCheckBoxAnimation = false;
            this.ShowPasswordBtn.AllowCheckmarkAnimation = true;
            this.ShowPasswordBtn.AllowOnHoverStates = true;
            this.ShowPasswordBtn.AutoCheck = true;
            this.ShowPasswordBtn.BackColor = System.Drawing.Color.Transparent;
            this.ShowPasswordBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("ShowPasswordBtn.BackgroundImage")));
            this.ShowPasswordBtn.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Zoom;
            this.ShowPasswordBtn.BindingControlPosition = Bunifu.UI.WinForms.BunifuCheckBox.BindingControlPositions.Right;
            this.ShowPasswordBtn.BorderRadius = 12;
            this.ShowPasswordBtn.Checked = false;
            this.ShowPasswordBtn.CheckState = Bunifu.UI.WinForms.BunifuCheckBox.CheckStates.Unchecked;
            this.ShowPasswordBtn.Cursor = System.Windows.Forms.Cursors.Default;
            this.ShowPasswordBtn.CustomCheckmarkImage = null;
            this.ShowPasswordBtn.Location = new System.Drawing.Point(343, 120);
            this.ShowPasswordBtn.MinimumSize = new System.Drawing.Size(17, 17);
            this.ShowPasswordBtn.Name = "ShowPasswordBtn";
            this.ShowPasswordBtn.OnCheck.BorderColor = System.Drawing.Color.SlateBlue;
            this.ShowPasswordBtn.OnCheck.BorderRadius = 12;
            this.ShowPasswordBtn.OnCheck.BorderThickness = 2;
            this.ShowPasswordBtn.OnCheck.CheckBoxColor = System.Drawing.Color.DarkSlateBlue;
            this.ShowPasswordBtn.OnCheck.CheckmarkColor = System.Drawing.Color.White;
            this.ShowPasswordBtn.OnCheck.CheckmarkThickness = 2;
            this.ShowPasswordBtn.OnDisable.BorderColor = System.Drawing.Color.LightGray;
            this.ShowPasswordBtn.OnDisable.BorderRadius = 12;
            this.ShowPasswordBtn.OnDisable.BorderThickness = 2;
            this.ShowPasswordBtn.OnDisable.CheckBoxColor = System.Drawing.Color.Transparent;
            this.ShowPasswordBtn.OnDisable.CheckmarkColor = System.Drawing.Color.LightGray;
            this.ShowPasswordBtn.OnDisable.CheckmarkThickness = 2;
            this.ShowPasswordBtn.OnHoverChecked.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.ShowPasswordBtn.OnHoverChecked.BorderRadius = 12;
            this.ShowPasswordBtn.OnHoverChecked.BorderThickness = 2;
            this.ShowPasswordBtn.OnHoverChecked.CheckBoxColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.ShowPasswordBtn.OnHoverChecked.CheckmarkColor = System.Drawing.Color.White;
            this.ShowPasswordBtn.OnHoverChecked.CheckmarkThickness = 2;
            this.ShowPasswordBtn.OnHoverUnchecked.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.ShowPasswordBtn.OnHoverUnchecked.BorderRadius = 12;
            this.ShowPasswordBtn.OnHoverUnchecked.BorderThickness = 1;
            this.ShowPasswordBtn.OnHoverUnchecked.CheckBoxColor = System.Drawing.Color.Transparent;
            this.ShowPasswordBtn.OnUncheck.BorderColor = System.Drawing.Color.DarkGray;
            this.ShowPasswordBtn.OnUncheck.BorderRadius = 12;
            this.ShowPasswordBtn.OnUncheck.BorderThickness = 1;
            this.ShowPasswordBtn.OnUncheck.CheckBoxColor = System.Drawing.Color.Transparent;
            this.ShowPasswordBtn.Size = new System.Drawing.Size(21, 21);
            this.ShowPasswordBtn.Style = Bunifu.UI.WinForms.BunifuCheckBox.CheckBoxStyles.Bunifu;
            this.ShowPasswordBtn.TabIndex = 14;
            this.ShowPasswordBtn.ThreeState = false;
            this.ShowPasswordBtn.ToolTipText = null;
            this.ShowPasswordBtn.CheckedChanged += new System.EventHandler<Bunifu.UI.WinForms.BunifuCheckBox.CheckedChangedEventArgs>(this.ShowPassword_CheckedChanged);
            // 
            // ShowPasswordText
            // 
            this.ShowPasswordText.AllowParentOverrides = false;
            this.ShowPasswordText.AutoEllipsis = false;
            this.ShowPasswordText.CursorType = null;
            this.ShowPasswordText.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.ShowPasswordText.ForeColor = System.Drawing.Color.Gray;
            this.ShowPasswordText.Location = new System.Drawing.Point(370, 120);
            this.ShowPasswordText.Name = "ShowPasswordText";
            this.ShowPasswordText.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.ShowPasswordText.Size = new System.Drawing.Size(100, 21);
            this.ShowPasswordText.TabIndex = 15;
            this.ShowPasswordText.Text = "Mostrar senha";
            this.ShowPasswordText.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.ShowPasswordText.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuPanel1
            // 
            this.bunifuPanel1.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(37)))), ((int)(((byte)(39)))), ((int)(((byte)(56)))));
            this.bunifuPanel1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuPanel1.BackgroundImage")));
            this.bunifuPanel1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuPanel1.BorderColor = System.Drawing.Color.Black;
            this.bunifuPanel1.BorderRadius = 1;
            this.bunifuPanel1.BorderThickness = 1;
            this.bunifuPanel1.Controls.Add(this.MostrarRegisterText);
            this.bunifuPanel1.Controls.Add(this.MostrarRegister);
            this.bunifuPanel1.Controls.Add(this.ReturnBtn);
            this.bunifuPanel1.Controls.Add(this.ConfirmButton);
            this.bunifuPanel1.Controls.Add(this.SenhaRegisterTxt);
            this.bunifuPanel1.Controls.Add(this.UsuarioRegisterTxt);
            this.bunifuPanel1.Controls.Add(this.DtaNascimentoRegisterTxt);
            this.bunifuPanel1.Controls.Add(this.SobrenomeRegisterTxt);
            this.bunifuPanel1.Controls.Add(this.NameRegisterTxt);
            this.bunifuPanel1.Controls.Add(this.DtaNascimento);
            this.bunifuPanel1.Controls.Add(this.PasswordText);
            this.bunifuPanel1.Controls.Add(this.UsuarioBtn);
            this.bunifuPanel1.Controls.Add(this.SobrenomeText);
            this.bunifuPanel1.Controls.Add(this.NameText);
            this.bunifuPanel1.Controls.Add(this.ConnectionStatus);
            this.bunifuPanel1.Controls.Add(this.bunifuLabel2);
            this.bunifuPanel1.Controls.Add(this.RegisterBtn);
            this.bunifuPanel1.Controls.Add(this.ShowPasswordText);
            this.bunifuPanel1.Controls.Add(this.ShowPasswordBtn);
            this.bunifuPanel1.Controls.Add(this.LoginBtn);
            this.bunifuPanel1.Controls.Add(this.UsernameTextBtn);
            this.bunifuPanel1.Controls.Add(this.MoreText);
            this.bunifuPanel1.Controls.Add(this.PasswordBtn);
            this.bunifuPanel1.Controls.Add(this.PasswordCheckBtn);
            this.bunifuPanel1.Location = new System.Drawing.Point(0, 125);
            this.bunifuPanel1.Name = "bunifuPanel1";
            this.bunifuPanel1.ShowBorders = true;
            this.bunifuPanel1.Size = new System.Drawing.Size(699, 203);
            this.bunifuPanel1.TabIndex = 16;
            this.bunifuPanel1.MouseDown += new System.Windows.Forms.MouseEventHandler(this.bunifuPanel1_MouseDown);
            // 
            // MostrarRegisterText
            // 
            this.MostrarRegisterText.AllowParentOverrides = false;
            this.MostrarRegisterText.AutoEllipsis = false;
            this.MostrarRegisterText.CursorType = null;
            this.MostrarRegisterText.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.MostrarRegisterText.ForeColor = System.Drawing.Color.Gray;
            this.MostrarRegisterText.Location = new System.Drawing.Point(533, 120);
            this.MostrarRegisterText.Name = "MostrarRegisterText";
            this.MostrarRegisterText.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.MostrarRegisterText.Size = new System.Drawing.Size(100, 21);
            this.MostrarRegisterText.TabIndex = 36;
            this.MostrarRegisterText.Text = "Mostrar senha";
            this.MostrarRegisterText.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.MostrarRegisterText.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.MostrarRegisterText.Visible = false;
            // 
            // MostrarRegister
            // 
            this.MostrarRegister.AllowBindingControlAnimation = true;
            this.MostrarRegister.AllowBindingControlColorChanges = false;
            this.MostrarRegister.AllowBindingControlLocation = true;
            this.MostrarRegister.AllowCheckBoxAnimation = false;
            this.MostrarRegister.AllowCheckmarkAnimation = true;
            this.MostrarRegister.AllowOnHoverStates = true;
            this.MostrarRegister.AutoCheck = true;
            this.MostrarRegister.BackColor = System.Drawing.Color.Transparent;
            this.MostrarRegister.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("MostrarRegister.BackgroundImage")));
            this.MostrarRegister.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Zoom;
            this.MostrarRegister.BindingControlPosition = Bunifu.UI.WinForms.BunifuCheckBox.BindingControlPositions.Right;
            this.MostrarRegister.BorderRadius = 12;
            this.MostrarRegister.Checked = false;
            this.MostrarRegister.CheckState = Bunifu.UI.WinForms.BunifuCheckBox.CheckStates.Unchecked;
            this.MostrarRegister.Cursor = System.Windows.Forms.Cursors.Default;
            this.MostrarRegister.CustomCheckmarkImage = null;
            this.MostrarRegister.Location = new System.Drawing.Point(483, 120);
            this.MostrarRegister.MinimumSize = new System.Drawing.Size(17, 17);
            this.MostrarRegister.Name = "MostrarRegister";
            this.MostrarRegister.OnCheck.BorderColor = System.Drawing.Color.SlateBlue;
            this.MostrarRegister.OnCheck.BorderRadius = 12;
            this.MostrarRegister.OnCheck.BorderThickness = 2;
            this.MostrarRegister.OnCheck.CheckBoxColor = System.Drawing.Color.DarkSlateBlue;
            this.MostrarRegister.OnCheck.CheckmarkColor = System.Drawing.Color.White;
            this.MostrarRegister.OnCheck.CheckmarkThickness = 2;
            this.MostrarRegister.OnDisable.BorderColor = System.Drawing.Color.LightGray;
            this.MostrarRegister.OnDisable.BorderRadius = 12;
            this.MostrarRegister.OnDisable.BorderThickness = 2;
            this.MostrarRegister.OnDisable.CheckBoxColor = System.Drawing.Color.Transparent;
            this.MostrarRegister.OnDisable.CheckmarkColor = System.Drawing.Color.LightGray;
            this.MostrarRegister.OnDisable.CheckmarkThickness = 2;
            this.MostrarRegister.OnHoverChecked.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.MostrarRegister.OnHoverChecked.BorderRadius = 12;
            this.MostrarRegister.OnHoverChecked.BorderThickness = 2;
            this.MostrarRegister.OnHoverChecked.CheckBoxColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.MostrarRegister.OnHoverChecked.CheckmarkColor = System.Drawing.Color.White;
            this.MostrarRegister.OnHoverChecked.CheckmarkThickness = 2;
            this.MostrarRegister.OnHoverUnchecked.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.MostrarRegister.OnHoverUnchecked.BorderRadius = 12;
            this.MostrarRegister.OnHoverUnchecked.BorderThickness = 1;
            this.MostrarRegister.OnHoverUnchecked.CheckBoxColor = System.Drawing.Color.Transparent;
            this.MostrarRegister.OnUncheck.BorderColor = System.Drawing.Color.DarkGray;
            this.MostrarRegister.OnUncheck.BorderRadius = 12;
            this.MostrarRegister.OnUncheck.BorderThickness = 1;
            this.MostrarRegister.OnUncheck.CheckBoxColor = System.Drawing.Color.Transparent;
            this.MostrarRegister.Size = new System.Drawing.Size(21, 21);
            this.MostrarRegister.Style = Bunifu.UI.WinForms.BunifuCheckBox.CheckBoxStyles.Bunifu;
            this.MostrarRegister.TabIndex = 35;
            this.MostrarRegister.ThreeState = false;
            this.MostrarRegister.ToolTipText = null;
            this.MostrarRegister.Visible = false;
            this.MostrarRegister.CheckedChanged += new System.EventHandler<Bunifu.UI.WinForms.BunifuCheckBox.CheckedChangedEventArgs>(this.MostrarRegister_CheckedChanged);
            // 
            // ReturnBtn
            // 
            this.ReturnBtn.ActiveImage = null;
            this.ReturnBtn.AllowAnimations = true;
            this.ReturnBtn.AllowBuffering = false;
            this.ReturnBtn.AllowToggling = false;
            this.ReturnBtn.AllowZooming = true;
            this.ReturnBtn.AllowZoomingOnFocus = false;
            this.ReturnBtn.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(37)))), ((int)(((byte)(39)))), ((int)(((byte)(56)))));
            this.ReturnBtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.ReturnBtn.ErrorImage = ((System.Drawing.Image)(resources.GetObject("ReturnBtn.ErrorImage")));
            this.ReturnBtn.FadeWhenInactive = false;
            this.ReturnBtn.Flip = Bunifu.UI.WinForms.BunifuImageButton.FlipOrientation.Normal;
            this.ReturnBtn.Image = ((System.Drawing.Image)(resources.GetObject("ReturnBtn.Image")));
            this.ReturnBtn.ImageActive = null;
            this.ReturnBtn.ImageLocation = null;
            this.ReturnBtn.ImageMargin = 0;
            this.ReturnBtn.ImageSize = new System.Drawing.Size(52, 51);
            this.ReturnBtn.ImageZoomSize = new System.Drawing.Size(53, 52);
            this.ReturnBtn.InitialImage = ((System.Drawing.Image)(resources.GetObject("ReturnBtn.InitialImage")));
            this.ReturnBtn.Location = new System.Drawing.Point(3, 147);
            this.ReturnBtn.Name = "ReturnBtn";
            this.ReturnBtn.Rotation = 0;
            this.ReturnBtn.ShowActiveImage = true;
            this.ReturnBtn.ShowCursorChanges = true;
            this.ReturnBtn.ShowImageBorders = true;
            this.ReturnBtn.ShowSizeMarkers = false;
            this.ReturnBtn.Size = new System.Drawing.Size(53, 52);
            this.ReturnBtn.TabIndex = 34;
            this.ReturnBtn.ToolTipText = "";
            this.ReturnBtn.WaitOnLoad = false;
            this.ReturnBtn.Zoom = 0;
            this.ReturnBtn.ZoomSpeed = 10;
            this.ReturnBtn.Click += new System.EventHandler(this.bunifuImageButton2_Click);
            // 
            // ConfirmButton
            // 
            this.ConfirmButton.AllowAnimations = true;
            this.ConfirmButton.AllowMouseEffects = true;
            this.ConfirmButton.AllowToggling = false;
            this.ConfirmButton.AnimationSpeed = 200;
            this.ConfirmButton.AutoGenerateColors = false;
            this.ConfirmButton.AutoRoundBorders = false;
            this.ConfirmButton.AutoSizeLeftIcon = true;
            this.ConfirmButton.AutoSizeRightIcon = true;
            this.ConfirmButton.BackColor = System.Drawing.Color.Transparent;
            this.ConfirmButton.BackColor1 = System.Drawing.Color.ForestGreen;
            this.ConfirmButton.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("ConfirmButton.BackgroundImage")));
            this.ConfirmButton.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.ConfirmButton.ButtonText = "Confirmar Registro";
            this.ConfirmButton.ButtonTextMarginLeft = 0;
            this.ConfirmButton.ColorContrastOnClick = 45;
            this.ConfirmButton.ColorContrastOnHover = 45;
            this.ConfirmButton.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.ConfirmButton.CustomizableEdges = borderEdges2;
            this.ConfirmButton.DialogResult = System.Windows.Forms.DialogResult.None;
            this.ConfirmButton.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.ConfirmButton.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.ConfirmButton.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.ConfirmButton.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.ConfirmButton.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.ConfirmButton.ForeColor = System.Drawing.Color.White;
            this.ConfirmButton.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.ConfirmButton.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.ConfirmButton.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.ConfirmButton.IconMarginLeft = 11;
            this.ConfirmButton.IconPadding = 10;
            this.ConfirmButton.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.ConfirmButton.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.ConfirmButton.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.ConfirmButton.IconSize = 25;
            this.ConfirmButton.IdleBorderColor = System.Drawing.Color.Silver;
            this.ConfirmButton.IdleBorderRadius = 1;
            this.ConfirmButton.IdleBorderThickness = 1;
            this.ConfirmButton.IdleFillColor = System.Drawing.Color.ForestGreen;
            this.ConfirmButton.IdleIconLeftImage = null;
            this.ConfirmButton.IdleIconRightImage = null;
            this.ConfirmButton.IndicateFocus = false;
            this.ConfirmButton.Location = new System.Drawing.Point(206, 147);
            this.ConfirmButton.Name = "ConfirmButton";
            this.ConfirmButton.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.ConfirmButton.OnDisabledState.BorderRadius = 1;
            this.ConfirmButton.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.ConfirmButton.OnDisabledState.BorderThickness = 1;
            this.ConfirmButton.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.ConfirmButton.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.ConfirmButton.OnDisabledState.IconLeftImage = null;
            this.ConfirmButton.OnDisabledState.IconRightImage = null;
            this.ConfirmButton.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(37)))), ((int)(((byte)(39)))), ((int)(((byte)(56)))));
            this.ConfirmButton.onHoverState.BorderRadius = 1;
            this.ConfirmButton.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.ConfirmButton.onHoverState.BorderThickness = 1;
            this.ConfirmButton.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(37)))), ((int)(((byte)(39)))), ((int)(((byte)(56)))));
            this.ConfirmButton.onHoverState.ForeColor = System.Drawing.Color.White;
            this.ConfirmButton.onHoverState.IconLeftImage = null;
            this.ConfirmButton.onHoverState.IconRightImage = null;
            this.ConfirmButton.OnIdleState.BorderColor = System.Drawing.Color.Silver;
            this.ConfirmButton.OnIdleState.BorderRadius = 1;
            this.ConfirmButton.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.ConfirmButton.OnIdleState.BorderThickness = 1;
            this.ConfirmButton.OnIdleState.FillColor = System.Drawing.Color.ForestGreen;
            this.ConfirmButton.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.ConfirmButton.OnIdleState.IconLeftImage = null;
            this.ConfirmButton.OnIdleState.IconRightImage = null;
            this.ConfirmButton.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(37)))), ((int)(((byte)(39)))), ((int)(((byte)(80)))));
            this.ConfirmButton.OnPressedState.BorderRadius = 1;
            this.ConfirmButton.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.ConfirmButton.OnPressedState.BorderThickness = 1;
            this.ConfirmButton.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(37)))), ((int)(((byte)(39)))), ((int)(((byte)(80)))));
            this.ConfirmButton.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.ConfirmButton.OnPressedState.IconLeftImage = null;
            this.ConfirmButton.OnPressedState.IconRightImage = null;
            this.ConfirmButton.Size = new System.Drawing.Size(260, 39);
            this.ConfirmButton.TabIndex = 33;
            this.ConfirmButton.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.ConfirmButton.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.ConfirmButton.TextMarginLeft = 0;
            this.ConfirmButton.TextPadding = new System.Windows.Forms.Padding(0);
            this.ConfirmButton.UseDefaultRadiusAndThickness = true;
            this.ConfirmButton.Visible = false;
            this.ConfirmButton.Click += new System.EventHandler(this.ConfirmButton_Click);
            // 
            // SenhaRegisterTxt
            // 
            this.SenhaRegisterTxt.AllowParentOverrides = false;
            this.SenhaRegisterTxt.AutoEllipsis = false;
            this.SenhaRegisterTxt.CursorType = null;
            this.SenhaRegisterTxt.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.SenhaRegisterTxt.ForeColor = System.Drawing.Color.Gray;
            this.SenhaRegisterTxt.Location = new System.Drawing.Point(483, 60);
            this.SenhaRegisterTxt.Name = "SenhaRegisterTxt";
            this.SenhaRegisterTxt.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.SenhaRegisterTxt.Size = new System.Drawing.Size(43, 21);
            this.SenhaRegisterTxt.TabIndex = 32;
            this.SenhaRegisterTxt.Text = "Senha";
            this.SenhaRegisterTxt.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.SenhaRegisterTxt.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.SenhaRegisterTxt.Visible = false;
            // 
            // UsuarioRegisterTxt
            // 
            this.UsuarioRegisterTxt.AllowParentOverrides = false;
            this.UsuarioRegisterTxt.AutoEllipsis = false;
            this.UsuarioRegisterTxt.CursorType = null;
            this.UsuarioRegisterTxt.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.UsuarioRegisterTxt.ForeColor = System.Drawing.Color.Gray;
            this.UsuarioRegisterTxt.Location = new System.Drawing.Point(483, 0);
            this.UsuarioRegisterTxt.Name = "UsuarioRegisterTxt";
            this.UsuarioRegisterTxt.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.UsuarioRegisterTxt.Size = new System.Drawing.Size(54, 21);
            this.UsuarioRegisterTxt.TabIndex = 31;
            this.UsuarioRegisterTxt.Text = "Usuario";
            this.UsuarioRegisterTxt.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.UsuarioRegisterTxt.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.UsuarioRegisterTxt.Visible = false;
            // 
            // DtaNascimentoRegisterTxt
            // 
            this.DtaNascimentoRegisterTxt.AllowParentOverrides = false;
            this.DtaNascimentoRegisterTxt.AutoEllipsis = false;
            this.DtaNascimentoRegisterTxt.CursorType = null;
            this.DtaNascimentoRegisterTxt.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.DtaNascimentoRegisterTxt.ForeColor = System.Drawing.Color.Gray;
            this.DtaNascimentoRegisterTxt.Location = new System.Drawing.Point(283, 0);
            this.DtaNascimentoRegisterTxt.Name = "DtaNascimentoRegisterTxt";
            this.DtaNascimentoRegisterTxt.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.DtaNascimentoRegisterTxt.Size = new System.Drawing.Size(140, 21);
            this.DtaNascimentoRegisterTxt.TabIndex = 29;
            this.DtaNascimentoRegisterTxt.Text = "Data de Nascimento";
            this.DtaNascimentoRegisterTxt.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.DtaNascimentoRegisterTxt.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.DtaNascimentoRegisterTxt.Visible = false;
            // 
            // SobrenomeRegisterTxt
            // 
            this.SobrenomeRegisterTxt.AllowParentOverrides = false;
            this.SobrenomeRegisterTxt.AutoEllipsis = false;
            this.SobrenomeRegisterTxt.CursorType = null;
            this.SobrenomeRegisterTxt.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.SobrenomeRegisterTxt.ForeColor = System.Drawing.Color.Gray;
            this.SobrenomeRegisterTxt.Location = new System.Drawing.Point(62, 60);
            this.SobrenomeRegisterTxt.Name = "SobrenomeRegisterTxt";
            this.SobrenomeRegisterTxt.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.SobrenomeRegisterTxt.Size = new System.Drawing.Size(81, 21);
            this.SobrenomeRegisterTxt.TabIndex = 28;
            this.SobrenomeRegisterTxt.Text = "Sobrenome";
            this.SobrenomeRegisterTxt.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.SobrenomeRegisterTxt.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.SobrenomeRegisterTxt.Visible = false;
            // 
            // NameRegisterTxt
            // 
            this.NameRegisterTxt.AllowParentOverrides = false;
            this.NameRegisterTxt.AutoEllipsis = false;
            this.NameRegisterTxt.CursorType = null;
            this.NameRegisterTxt.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.NameRegisterTxt.ForeColor = System.Drawing.Color.Gray;
            this.NameRegisterTxt.Location = new System.Drawing.Point(62, 0);
            this.NameRegisterTxt.Name = "NameRegisterTxt";
            this.NameRegisterTxt.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.NameRegisterTxt.Size = new System.Drawing.Size(43, 21);
            this.NameRegisterTxt.TabIndex = 27;
            this.NameRegisterTxt.Text = "Nome";
            this.NameRegisterTxt.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.NameRegisterTxt.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.NameRegisterTxt.Visible = false;
            // 
            // DtaNascimento
            // 
            this.DtaNascimento.BackColor = System.Drawing.Color.White;
            this.DtaNascimento.BorderRadius = 1;
            this.DtaNascimento.CalendarForeColor = System.Drawing.Color.Black;
            this.DtaNascimento.CalendarTitleForeColor = System.Drawing.Color.Silver;
            this.DtaNascimento.CalendarTrailingForeColor = System.Drawing.SystemColors.ControlText;
            this.DtaNascimento.Color = System.Drawing.Color.Silver;
            this.DtaNascimento.DateBorderThickness = Bunifu.UI.WinForms.BunifuDatePicker.BorderThickness.Thin;
            this.DtaNascimento.DateTextAlign = Bunifu.UI.WinForms.BunifuDatePicker.TextAlign.Left;
            this.DtaNascimento.DisabledColor = System.Drawing.Color.Gray;
            this.DtaNascimento.DisplayWeekNumbers = false;
            this.DtaNascimento.DPHeight = 0;
            this.DtaNascimento.DropDownAlign = System.Windows.Forms.LeftRightAlignment.Right;
            this.DtaNascimento.FillDatePicker = false;
            this.DtaNascimento.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.DtaNascimento.ForeColor = System.Drawing.Color.Black;
            this.DtaNascimento.Format = System.Windows.Forms.DateTimePickerFormat.Short;
            this.DtaNascimento.Icon = ((System.Drawing.Image)(resources.GetObject("DtaNascimento.Icon")));
            this.DtaNascimento.IconColor = System.Drawing.Color.Gray;
            this.DtaNascimento.IconLocation = Bunifu.UI.WinForms.BunifuDatePicker.Indicator.Right;
            this.DtaNascimento.LeftTextMargin = 5;
            this.DtaNascimento.Location = new System.Drawing.Point(283, 22);
            this.DtaNascimento.MinimumSize = new System.Drawing.Size(4, 32);
            this.DtaNascimento.Name = "DtaNascimento";
            this.DtaNascimento.Size = new System.Drawing.Size(127, 32);
            this.DtaNascimento.TabIndex = 23;
            this.DtaNascimento.Visible = false;
            // 
            // PasswordText
            // 
            this.PasswordText.AcceptsReturn = false;
            this.PasswordText.AcceptsTab = false;
            this.PasswordText.AnimationSpeed = 200;
            this.PasswordText.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.PasswordText.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.PasswordText.BackColor = System.Drawing.Color.Transparent;
            this.PasswordText.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("PasswordText.BackgroundImage")));
            this.PasswordText.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.PasswordText.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.PasswordText.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.PasswordText.BorderColorIdle = System.Drawing.Color.White;
            this.PasswordText.BorderRadius = 1;
            this.PasswordText.BorderThickness = 1;
            this.PasswordText.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.PasswordText.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.PasswordText.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.PasswordText.DefaultText = "";
            this.PasswordText.FillColor = System.Drawing.Color.White;
            this.PasswordText.ForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            this.PasswordText.HideSelection = true;
            this.PasswordText.IconLeft = null;
            this.PasswordText.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.PasswordText.IconPadding = 10;
            this.PasswordText.IconRight = null;
            this.PasswordText.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.PasswordText.Lines = new string[0];
            this.PasswordText.Location = new System.Drawing.Point(483, 82);
            this.PasswordText.MaxLength = 20;
            this.PasswordText.MinimumSize = new System.Drawing.Size(1, 1);
            this.PasswordText.Modified = false;
            this.PasswordText.Multiline = false;
            this.PasswordText.Name = "PasswordText";
            stateProperties9.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.PasswordText.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(192)))), ((int)(((byte)(192)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.PasswordText.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.PasswordText.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.White;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.PasswordText.OnIdleState = stateProperties12;
            this.PasswordText.Padding = new System.Windows.Forms.Padding(3);
            this.PasswordText.PasswordChar = '•';
            this.PasswordText.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.PasswordText.PlaceholderText = "Senha";
            this.PasswordText.ReadOnly = false;
            this.PasswordText.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.PasswordText.SelectedText = "";
            this.PasswordText.SelectionLength = 0;
            this.PasswordText.SelectionStart = 0;
            this.PasswordText.ShortcutsEnabled = true;
            this.PasswordText.Size = new System.Drawing.Size(150, 32);
            this.PasswordText.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.PasswordText.TabIndex = 22;
            this.PasswordText.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.PasswordText.TextMarginBottom = 0;
            this.PasswordText.TextMarginLeft = 3;
            this.PasswordText.TextMarginTop = 0;
            this.PasswordText.TextPlaceholder = "Senha";
            this.PasswordText.UseSystemPasswordChar = false;
            this.PasswordText.Visible = false;
            this.PasswordText.WordWrap = true;
            // 
            // UsuarioBtn
            // 
            this.UsuarioBtn.AcceptsReturn = false;
            this.UsuarioBtn.AcceptsTab = false;
            this.UsuarioBtn.AnimationSpeed = 200;
            this.UsuarioBtn.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.UsuarioBtn.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.UsuarioBtn.BackColor = System.Drawing.Color.Transparent;
            this.UsuarioBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("UsuarioBtn.BackgroundImage")));
            this.UsuarioBtn.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.UsuarioBtn.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.UsuarioBtn.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.UsuarioBtn.BorderColorIdle = System.Drawing.Color.White;
            this.UsuarioBtn.BorderRadius = 1;
            this.UsuarioBtn.BorderThickness = 1;
            this.UsuarioBtn.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.UsuarioBtn.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.UsuarioBtn.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.UsuarioBtn.DefaultText = "";
            this.UsuarioBtn.FillColor = System.Drawing.Color.White;
            this.UsuarioBtn.ForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            this.UsuarioBtn.HideSelection = true;
            this.UsuarioBtn.IconLeft = null;
            this.UsuarioBtn.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.UsuarioBtn.IconPadding = 10;
            this.UsuarioBtn.IconRight = null;
            this.UsuarioBtn.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.UsuarioBtn.Lines = new string[0];
            this.UsuarioBtn.Location = new System.Drawing.Point(483, 22);
            this.UsuarioBtn.MaxLength = 20;
            this.UsuarioBtn.MinimumSize = new System.Drawing.Size(1, 1);
            this.UsuarioBtn.Modified = false;
            this.UsuarioBtn.Multiline = false;
            this.UsuarioBtn.Name = "UsuarioBtn";
            stateProperties13.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.UsuarioBtn.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(192)))), ((int)(((byte)(192)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.UsuarioBtn.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.UsuarioBtn.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.White;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.UsuarioBtn.OnIdleState = stateProperties16;
            this.UsuarioBtn.Padding = new System.Windows.Forms.Padding(3);
            this.UsuarioBtn.PasswordChar = '\0';
            this.UsuarioBtn.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.UsuarioBtn.PlaceholderText = "Usuario";
            this.UsuarioBtn.ReadOnly = false;
            this.UsuarioBtn.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.UsuarioBtn.SelectedText = "";
            this.UsuarioBtn.SelectionLength = 0;
            this.UsuarioBtn.SelectionStart = 0;
            this.UsuarioBtn.ShortcutsEnabled = true;
            this.UsuarioBtn.Size = new System.Drawing.Size(150, 32);
            this.UsuarioBtn.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.UsuarioBtn.TabIndex = 21;
            this.UsuarioBtn.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.UsuarioBtn.TextMarginBottom = 0;
            this.UsuarioBtn.TextMarginLeft = 3;
            this.UsuarioBtn.TextMarginTop = 0;
            this.UsuarioBtn.TextPlaceholder = "Usuario";
            this.UsuarioBtn.UseSystemPasswordChar = false;
            this.UsuarioBtn.Visible = false;
            this.UsuarioBtn.WordWrap = true;
            // 
            // SobrenomeText
            // 
            this.SobrenomeText.AcceptsReturn = false;
            this.SobrenomeText.AcceptsTab = false;
            this.SobrenomeText.AnimationSpeed = 200;
            this.SobrenomeText.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.SobrenomeText.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.SobrenomeText.BackColor = System.Drawing.Color.Transparent;
            this.SobrenomeText.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("SobrenomeText.BackgroundImage")));
            this.SobrenomeText.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.SobrenomeText.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.SobrenomeText.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.SobrenomeText.BorderColorIdle = System.Drawing.Color.White;
            this.SobrenomeText.BorderRadius = 1;
            this.SobrenomeText.BorderThickness = 1;
            this.SobrenomeText.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.SobrenomeText.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.SobrenomeText.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.SobrenomeText.DefaultText = "";
            this.SobrenomeText.FillColor = System.Drawing.Color.White;
            this.SobrenomeText.ForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            this.SobrenomeText.HideSelection = true;
            this.SobrenomeText.IconLeft = null;
            this.SobrenomeText.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.SobrenomeText.IconPadding = 10;
            this.SobrenomeText.IconRight = null;
            this.SobrenomeText.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.SobrenomeText.Lines = new string[0];
            this.SobrenomeText.Location = new System.Drawing.Point(62, 82);
            this.SobrenomeText.MaxLength = 60;
            this.SobrenomeText.MinimumSize = new System.Drawing.Size(1, 1);
            this.SobrenomeText.Modified = false;
            this.SobrenomeText.Multiline = false;
            this.SobrenomeText.Name = "SobrenomeText";
            stateProperties17.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.SobrenomeText.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(192)))), ((int)(((byte)(192)))));
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.SobrenomeText.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.SobrenomeText.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.White;
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.SobrenomeText.OnIdleState = stateProperties20;
            this.SobrenomeText.Padding = new System.Windows.Forms.Padding(3);
            this.SobrenomeText.PasswordChar = '\0';
            this.SobrenomeText.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.SobrenomeText.PlaceholderText = "Sobrenome";
            this.SobrenomeText.ReadOnly = false;
            this.SobrenomeText.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.SobrenomeText.SelectedText = "";
            this.SobrenomeText.SelectionLength = 0;
            this.SobrenomeText.SelectionStart = 0;
            this.SobrenomeText.ShortcutsEnabled = true;
            this.SobrenomeText.Size = new System.Drawing.Size(150, 32);
            this.SobrenomeText.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.SobrenomeText.TabIndex = 20;
            this.SobrenomeText.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.SobrenomeText.TextMarginBottom = 0;
            this.SobrenomeText.TextMarginLeft = 3;
            this.SobrenomeText.TextMarginTop = 0;
            this.SobrenomeText.TextPlaceholder = "Sobrenome";
            this.SobrenomeText.UseSystemPasswordChar = false;
            this.SobrenomeText.Visible = false;
            this.SobrenomeText.WordWrap = true;
            this.SobrenomeText.KeyPress += new System.Windows.Forms.KeyPressEventHandler(this.SobrenomeText_KeyPress);
            // 
            // NameText
            // 
            this.NameText.AcceptsReturn = false;
            this.NameText.AcceptsTab = false;
            this.NameText.AnimationSpeed = 200;
            this.NameText.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.NameText.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.NameText.BackColor = System.Drawing.Color.Transparent;
            this.NameText.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("NameText.BackgroundImage")));
            this.NameText.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.NameText.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.NameText.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.NameText.BorderColorIdle = System.Drawing.Color.White;
            this.NameText.BorderRadius = 1;
            this.NameText.BorderThickness = 1;
            this.NameText.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.NameText.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.NameText.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.NameText.DefaultText = "";
            this.NameText.FillColor = System.Drawing.Color.White;
            this.NameText.ForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            this.NameText.HideSelection = true;
            this.NameText.IconLeft = null;
            this.NameText.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.NameText.IconPadding = 10;
            this.NameText.IconRight = null;
            this.NameText.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.NameText.Lines = new string[0];
            this.NameText.Location = new System.Drawing.Point(62, 22);
            this.NameText.MaxLength = 50;
            this.NameText.MinimumSize = new System.Drawing.Size(1, 1);
            this.NameText.Modified = false;
            this.NameText.Multiline = false;
            this.NameText.Name = "NameText";
            stateProperties21.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties21.FillColor = System.Drawing.Color.Empty;
            stateProperties21.ForeColor = System.Drawing.Color.Empty;
            stateProperties21.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.NameText.OnActiveState = stateProperties21;
            stateProperties22.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties22.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(192)))), ((int)(((byte)(192)))));
            stateProperties22.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties22.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.NameText.OnDisabledState = stateProperties22;
            stateProperties23.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties23.FillColor = System.Drawing.Color.Empty;
            stateProperties23.ForeColor = System.Drawing.Color.Empty;
            stateProperties23.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.NameText.OnHoverState = stateProperties23;
            stateProperties24.BorderColor = System.Drawing.Color.White;
            stateProperties24.FillColor = System.Drawing.Color.White;
            stateProperties24.ForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            stateProperties24.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.NameText.OnIdleState = stateProperties24;
            this.NameText.Padding = new System.Windows.Forms.Padding(3);
            this.NameText.PasswordChar = '\0';
            this.NameText.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.NameText.PlaceholderText = "Nome";
            this.NameText.ReadOnly = false;
            this.NameText.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.NameText.SelectedText = "";
            this.NameText.SelectionLength = 0;
            this.NameText.SelectionStart = 0;
            this.NameText.ShortcutsEnabled = true;
            this.NameText.Size = new System.Drawing.Size(150, 32);
            this.NameText.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.NameText.TabIndex = 19;
            this.NameText.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.NameText.TextMarginBottom = 0;
            this.NameText.TextMarginLeft = 3;
            this.NameText.TextMarginTop = 0;
            this.NameText.TextPlaceholder = "Nome";
            this.NameText.UseSystemPasswordChar = false;
            this.NameText.Visible = false;
            this.NameText.WordWrap = true;
            this.NameText.KeyPress += new System.Windows.Forms.KeyPressEventHandler(this.NameText_KeyPress);
            // 
            // ConnectionStatus
            // 
            this.ConnectionStatus.AllowParentOverrides = false;
            this.ConnectionStatus.AutoEllipsis = false;
            this.ConnectionStatus.CursorType = null;
            this.ConnectionStatus.Font = new System.Drawing.Font("Segoe UI", 6F);
            this.ConnectionStatus.ForeColor = System.Drawing.Color.Gray;
            this.ConnectionStatus.Location = new System.Drawing.Point(579, 190);
            this.ConnectionStatus.Name = "ConnectionStatus";
            this.ConnectionStatus.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.ConnectionStatus.Size = new System.Drawing.Size(0, 0);
            this.ConnectionStatus.TabIndex = 18;
            this.ConnectionStatus.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.ConnectionStatus.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel2
            // 
            this.bunifuLabel2.AllowParentOverrides = false;
            this.bunifuLabel2.AutoEllipsis = false;
            this.bunifuLabel2.CursorType = null;
            this.bunifuLabel2.Font = new System.Drawing.Font("Segoe UI", 6F);
            this.bunifuLabel2.ForeColor = System.Drawing.Color.Gray;
            this.bunifuLabel2.Location = new System.Drawing.Point(451, 190);
            this.bunifuLabel2.Name = "bunifuLabel2";
            this.bunifuLabel2.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel2.Size = new System.Drawing.Size(124, 11);
            this.bunifuLabel2.TabIndex = 17;
            this.bunifuLabel2.Text = "Status de conexão com o servidor: ";
            this.bunifuLabel2.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel2.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // RegisterBtn
            // 
            this.RegisterBtn.AllowAnimations = true;
            this.RegisterBtn.AllowMouseEffects = true;
            this.RegisterBtn.AllowToggling = false;
            this.RegisterBtn.AnimationSpeed = 200;
            this.RegisterBtn.AutoGenerateColors = false;
            this.RegisterBtn.AutoRoundBorders = false;
            this.RegisterBtn.AutoSizeLeftIcon = true;
            this.RegisterBtn.AutoSizeRightIcon = true;
            this.RegisterBtn.BackColor = System.Drawing.Color.Transparent;
            this.RegisterBtn.BackColor1 = System.Drawing.Color.ForestGreen;
            this.RegisterBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("RegisterBtn.BackgroundImage")));
            this.RegisterBtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.RegisterBtn.ButtonText = "Registrar-se";
            this.RegisterBtn.ButtonTextMarginLeft = 0;
            this.RegisterBtn.ColorContrastOnClick = 45;
            this.RegisterBtn.ColorContrastOnHover = 45;
            this.RegisterBtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.RegisterBtn.CustomizableEdges = borderEdges3;
            this.RegisterBtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.RegisterBtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.RegisterBtn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.RegisterBtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.RegisterBtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.RegisterBtn.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.RegisterBtn.ForeColor = System.Drawing.Color.White;
            this.RegisterBtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.RegisterBtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.RegisterBtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.RegisterBtn.IconMarginLeft = 11;
            this.RegisterBtn.IconPadding = 10;
            this.RegisterBtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.RegisterBtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.RegisterBtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.RegisterBtn.IconSize = 25;
            this.RegisterBtn.IdleBorderColor = System.Drawing.Color.Silver;
            this.RegisterBtn.IdleBorderRadius = 1;
            this.RegisterBtn.IdleBorderThickness = 1;
            this.RegisterBtn.IdleFillColor = System.Drawing.Color.ForestGreen;
            this.RegisterBtn.IdleIconLeftImage = null;
            this.RegisterBtn.IdleIconRightImage = null;
            this.RegisterBtn.IndicateFocus = false;
            this.RegisterBtn.Location = new System.Drawing.Point(343, 147);
            this.RegisterBtn.Name = "RegisterBtn";
            this.RegisterBtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.RegisterBtn.OnDisabledState.BorderRadius = 1;
            this.RegisterBtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.RegisterBtn.OnDisabledState.BorderThickness = 1;
            this.RegisterBtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.RegisterBtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.RegisterBtn.OnDisabledState.IconLeftImage = null;
            this.RegisterBtn.OnDisabledState.IconRightImage = null;
            this.RegisterBtn.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(37)))), ((int)(((byte)(39)))), ((int)(((byte)(56)))));
            this.RegisterBtn.onHoverState.BorderRadius = 1;
            this.RegisterBtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.RegisterBtn.onHoverState.BorderThickness = 1;
            this.RegisterBtn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(37)))), ((int)(((byte)(39)))), ((int)(((byte)(56)))));
            this.RegisterBtn.onHoverState.ForeColor = System.Drawing.Color.White;
            this.RegisterBtn.onHoverState.IconLeftImage = null;
            this.RegisterBtn.onHoverState.IconRightImage = null;
            this.RegisterBtn.OnIdleState.BorderColor = System.Drawing.Color.Silver;
            this.RegisterBtn.OnIdleState.BorderRadius = 1;
            this.RegisterBtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.RegisterBtn.OnIdleState.BorderThickness = 1;
            this.RegisterBtn.OnIdleState.FillColor = System.Drawing.Color.ForestGreen;
            this.RegisterBtn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.RegisterBtn.OnIdleState.IconLeftImage = null;
            this.RegisterBtn.OnIdleState.IconRightImage = null;
            this.RegisterBtn.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(37)))), ((int)(((byte)(39)))), ((int)(((byte)(80)))));
            this.RegisterBtn.OnPressedState.BorderRadius = 1;
            this.RegisterBtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.RegisterBtn.OnPressedState.BorderThickness = 1;
            this.RegisterBtn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(37)))), ((int)(((byte)(39)))), ((int)(((byte)(80)))));
            this.RegisterBtn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.RegisterBtn.OnPressedState.IconLeftImage = null;
            this.RegisterBtn.OnPressedState.IconRightImage = null;
            this.RegisterBtn.Size = new System.Drawing.Size(123, 39);
            this.RegisterBtn.TabIndex = 16;
            this.RegisterBtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.RegisterBtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.RegisterBtn.TextMarginLeft = 0;
            this.RegisterBtn.TextPadding = new System.Windows.Forms.Padding(0);
            this.RegisterBtn.UseDefaultRadiusAndThickness = true;
            this.RegisterBtn.Click += new System.EventHandler(this.RegisterBtn_Click);
            // 
            // LoginForm
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.AutoValidate = System.Windows.Forms.AutoValidate.Disable;
            this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(43)))), ((int)(((byte)(68)))));
            this.ClientSize = new System.Drawing.Size(700, 330);
            this.Controls.Add(this.bunifuPanel1);
            this.Controls.Add(this.pictureBox1);
            this.Controls.Add(this.MinimizeBtn);
            this.Controls.Add(this.bunifuImageButton1);
            this.ForeColor = System.Drawing.SystemColors.ButtonFace;
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
            this.KeyPreview = true;
            this.Name = "LoginForm";
            this.SizeGripStyle = System.Windows.Forms.SizeGripStyle.Show;
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Ergo";
            this.Load += new System.EventHandler(this.LoginForm_Load_1);
            this.MouseDown += new System.Windows.Forms.MouseEventHandler(this.LoginForm_MouseDown);
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).EndInit();
            this.bunifuPanel1.ResumeLayout(false);
            this.bunifuPanel1.PerformLayout();
            this.ResumeLayout(false);

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuImageButton bunifuImageButton1;
        private Bunifu.UI.WinForms.BunifuImageButton MinimizeBtn;
        private Bunifu.UI.WinForms.BunifuCheckBox PasswordCheckBtn;
        private Bunifu.UI.WinForms.BunifuTextBox UsernameTextBtn;
        private Bunifu.UI.WinForms.BunifuTextBox PasswordBtn;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton LoginBtn;
        private System.Windows.Forms.PictureBox pictureBox1;
        private Bunifu.UI.WinForms.BunifuLabel MoreText;
        private Bunifu.UI.WinForms.BunifuCheckBox ShowPasswordBtn;
        private Bunifu.UI.WinForms.BunifuLabel ShowPasswordText;
        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton RegisterBtn;
        private Bunifu.UI.WinForms.BunifuLabel ConnectionStatus;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel2;
        private Bunifu.UI.WinForms.BunifuDatePicker DtaNascimento;
        private Bunifu.UI.WinForms.BunifuTextBox PasswordText;
        private Bunifu.UI.WinForms.BunifuTextBox UsuarioBtn;
        private Bunifu.UI.WinForms.BunifuTextBox SobrenomeText;
        private Bunifu.UI.WinForms.BunifuTextBox NameText;
        private Bunifu.UI.WinForms.BunifuLabel SenhaRegisterTxt;
        private Bunifu.UI.WinForms.BunifuLabel UsuarioRegisterTxt;
        private Bunifu.UI.WinForms.BunifuLabel DtaNascimentoRegisterTxt;
        private Bunifu.UI.WinForms.BunifuLabel SobrenomeRegisterTxt;
        private Bunifu.UI.WinForms.BunifuLabel NameRegisterTxt;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton ConfirmButton;
        private Bunifu.UI.WinForms.BunifuImageButton ReturnBtn;
        private Bunifu.UI.WinForms.BunifuLabel MostrarRegisterText;
        private Bunifu.UI.WinForms.BunifuCheckBox MostrarRegister;
    }
}

