
namespace InterfaceErgonomico
{
    partial class Principal
    {
        /// <summary>
        /// Variável de designer necessária.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Limpar os recursos que estão sendo usados.
        /// </summary>
        /// <param name="disposing">true se for necessário descartar os recursos gerenciados; caso contrário, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Código gerado pelo Windows Form Designer

        /// <summary>
        /// Método necessário para suporte ao Designer - não modifique 
        /// o conteúdo deste método com o editor de código.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Principal));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges22 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges23 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges24 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges25 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges26 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges27 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges28 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.panel1 = new System.Windows.Forms.Panel();
            this.LicenseBtn = new Bunifu.UI.WinForms.BunifuImageButton();
            this.StartLogoutBtn = new Bunifu.UI.WinForms.BunifuImageButton();
            this.MoreText = new Bunifu.UI.WinForms.BunifuLabel();
            this.PrincipalText = new Bunifu.UI.WinForms.BunifuLabel();
            this.BookBtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.AboutBtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.DashboardBtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.TimeBtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.LiquidBtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.ErgoBtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.ConfigBtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.Logo = new Bunifu.UI.WinForms.BunifuPictureBox();
            this.bunifuImageButton1 = new Bunifu.UI.WinForms.BunifuImageButton();
            this.SearchBtn = new Bunifu.UI.WinForms.BunifuImageButton();
            this.NotificationBtn = new Bunifu.UI.WinForms.BunifuImageButton();
            this.UserLogged = new Bunifu.UI.WinForms.BunifuPictureBox();
            this.MinimizeBtn = new Bunifu.UI.WinForms.BunifuImageButton();
            this.panel1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.Logo)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.UserLogged)).BeginInit();
            this.SuspendLayout();
            // 
            // panel1
            // 
            this.panel1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(43)))), ((int)(((byte)(72)))));
            this.panel1.Controls.Add(this.LicenseBtn);
            this.panel1.Controls.Add(this.StartLogoutBtn);
            this.panel1.Controls.Add(this.MoreText);
            this.panel1.Controls.Add(this.PrincipalText);
            this.panel1.Controls.Add(this.BookBtn);
            this.panel1.Controls.Add(this.AboutBtn);
            this.panel1.Controls.Add(this.DashboardBtn);
            this.panel1.Controls.Add(this.TimeBtn);
            this.panel1.Controls.Add(this.LiquidBtn);
            this.panel1.Controls.Add(this.ErgoBtn);
            this.panel1.Controls.Add(this.ConfigBtn);
            this.panel1.Controls.Add(this.Logo);
            this.panel1.Dock = System.Windows.Forms.DockStyle.Left;
            this.panel1.Location = new System.Drawing.Point(0, 0);
            this.panel1.Name = "panel1";
            this.panel1.Size = new System.Drawing.Size(247, 644);
            this.panel1.TabIndex = 0;
            this.panel1.MouseDown += new System.Windows.Forms.MouseEventHandler(this.panel1_MouseDown);
            // 
            // LicenseBtn
            // 
            this.LicenseBtn.ActiveImage = null;
            this.LicenseBtn.AllowAnimations = true;
            this.LicenseBtn.AllowBuffering = false;
            this.LicenseBtn.AllowToggling = false;
            this.LicenseBtn.AllowZooming = true;
            this.LicenseBtn.AllowZoomingOnFocus = false;
            this.LicenseBtn.BackColor = System.Drawing.Color.Transparent;
            this.LicenseBtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.LicenseBtn.ErrorImage = ((System.Drawing.Image)(resources.GetObject("LicenseBtn.ErrorImage")));
            this.LicenseBtn.FadeWhenInactive = false;
            this.LicenseBtn.Flip = Bunifu.UI.WinForms.BunifuImageButton.FlipOrientation.Normal;
            this.LicenseBtn.Image = ((System.Drawing.Image)(resources.GetObject("LicenseBtn.Image")));
            this.LicenseBtn.ImageActive = null;
            this.LicenseBtn.ImageLocation = null;
            this.LicenseBtn.ImageMargin = 0;
            this.LicenseBtn.ImageSize = new System.Drawing.Size(39, 39);
            this.LicenseBtn.ImageZoomSize = new System.Drawing.Size(40, 40);
            this.LicenseBtn.InitialImage = ((System.Drawing.Image)(resources.GetObject("LicenseBtn.InitialImage")));
            this.LicenseBtn.Location = new System.Drawing.Point(204, 592);
            this.LicenseBtn.Name = "LicenseBtn";
            this.LicenseBtn.Rotation = 0;
            this.LicenseBtn.ShowActiveImage = true;
            this.LicenseBtn.ShowCursorChanges = true;
            this.LicenseBtn.ShowImageBorders = true;
            this.LicenseBtn.ShowSizeMarkers = false;
            this.LicenseBtn.Size = new System.Drawing.Size(40, 40);
            this.LicenseBtn.TabIndex = 7;
            this.LicenseBtn.ToolTipText = "License";
            this.LicenseBtn.WaitOnLoad = false;
            this.LicenseBtn.Zoom = 0;
            this.LicenseBtn.ZoomSpeed = 10;
            this.LicenseBtn.Click += new System.EventHandler(this.bunifuImageButton2_Click);
            // 
            // StartLogoutBtn
            // 
            this.StartLogoutBtn.ActiveImage = null;
            this.StartLogoutBtn.AllowAnimations = true;
            this.StartLogoutBtn.AllowBuffering = false;
            this.StartLogoutBtn.AllowToggling = false;
            this.StartLogoutBtn.AllowZooming = true;
            this.StartLogoutBtn.AllowZoomingOnFocus = false;
            this.StartLogoutBtn.BackColor = System.Drawing.Color.Transparent;
            this.StartLogoutBtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.StartLogoutBtn.ErrorImage = ((System.Drawing.Image)(resources.GetObject("StartLogoutBtn.ErrorImage")));
            this.StartLogoutBtn.FadeWhenInactive = false;
            this.StartLogoutBtn.Flip = Bunifu.UI.WinForms.BunifuImageButton.FlipOrientation.Normal;
            this.StartLogoutBtn.Image = ((System.Drawing.Image)(resources.GetObject("StartLogoutBtn.Image")));
            this.StartLogoutBtn.ImageActive = null;
            this.StartLogoutBtn.ImageLocation = null;
            this.StartLogoutBtn.ImageMargin = 0;
            this.StartLogoutBtn.ImageSize = new System.Drawing.Size(94, 93);
            this.StartLogoutBtn.ImageZoomSize = new System.Drawing.Size(95, 94);
            this.StartLogoutBtn.InitialImage = ((System.Drawing.Image)(resources.GetObject("StartLogoutBtn.InitialImage")));
            this.StartLogoutBtn.Location = new System.Drawing.Point(73, 547);
            this.StartLogoutBtn.Name = "StartLogoutBtn";
            this.StartLogoutBtn.Rotation = 0;
            this.StartLogoutBtn.ShowActiveImage = true;
            this.StartLogoutBtn.ShowCursorChanges = true;
            this.StartLogoutBtn.ShowImageBorders = true;
            this.StartLogoutBtn.ShowSizeMarkers = false;
            this.StartLogoutBtn.Size = new System.Drawing.Size(95, 94);
            this.StartLogoutBtn.TabIndex = 1;
            this.StartLogoutBtn.ToolTipText = "Logout";
            this.StartLogoutBtn.WaitOnLoad = false;
            this.StartLogoutBtn.Zoom = 0;
            this.StartLogoutBtn.ZoomSpeed = 10;
            this.StartLogoutBtn.Click += new System.EventHandler(this.bunifuImageButton1_Click);
            // 
            // MoreText
            // 
            this.MoreText.AllowParentOverrides = false;
            this.MoreText.AutoEllipsis = false;
            this.MoreText.CursorType = null;
            this.MoreText.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.MoreText.ForeColor = System.Drawing.Color.Gray;
            this.MoreText.Location = new System.Drawing.Point(91, 412);
            this.MoreText.Name = "MoreText";
            this.MoreText.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.MoreText.Size = new System.Drawing.Size(33, 21);
            this.MoreText.TabIndex = 6;
            this.MoreText.Text = "Mais";
            this.MoreText.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.MoreText.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // PrincipalText
            // 
            this.PrincipalText.AllowParentOverrides = false;
            this.PrincipalText.AutoEllipsis = false;
            this.PrincipalText.Cursor = System.Windows.Forms.Cursors.Default;
            this.PrincipalText.CursorType = System.Windows.Forms.Cursors.Default;
            this.PrincipalText.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.PrincipalText.ForeColor = System.Drawing.Color.Gray;
            this.PrincipalText.Location = new System.Drawing.Point(91, 115);
            this.PrincipalText.Name = "PrincipalText";
            this.PrincipalText.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.PrincipalText.Size = new System.Drawing.Size(60, 21);
            this.PrincipalText.TabIndex = 5;
            this.PrincipalText.Text = "Principal";
            this.PrincipalText.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.PrincipalText.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.PrincipalText.Click += new System.EventHandler(this.bunifuLabel1_Click);
            // 
            // BookBtn
            // 
            this.BookBtn.AllowAnimations = true;
            this.BookBtn.AllowMouseEffects = true;
            this.BookBtn.AllowToggling = false;
            this.BookBtn.AnimationSpeed = 200;
            this.BookBtn.AutoGenerateColors = false;
            this.BookBtn.AutoRoundBorders = false;
            this.BookBtn.AutoSizeLeftIcon = true;
            this.BookBtn.AutoSizeRightIcon = true;
            this.BookBtn.BackColor = System.Drawing.Color.Transparent;
            this.BookBtn.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(43)))), ((int)(((byte)(72)))));
            this.BookBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("BookBtn.BackgroundImage")));
            this.BookBtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BookBtn.ButtonText = "Dicas E-book";
            this.BookBtn.ButtonTextMarginLeft = 0;
            this.BookBtn.ColorContrastOnClick = 45;
            this.BookBtn.ColorContrastOnHover = 45;
            this.BookBtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges22.BottomLeft = true;
            borderEdges22.BottomRight = true;
            borderEdges22.TopLeft = true;
            borderEdges22.TopRight = true;
            this.BookBtn.CustomizableEdges = borderEdges22;
            this.BookBtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.BookBtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BookBtn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BookBtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BookBtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.BookBtn.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.BookBtn.ForeColor = System.Drawing.Color.White;
            this.BookBtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.BookBtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.BookBtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.BookBtn.IconMarginLeft = 11;
            this.BookBtn.IconPadding = 5;
            this.BookBtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.BookBtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.BookBtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.BookBtn.IconSize = 25;
            this.BookBtn.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(43)))), ((int)(((byte)(72)))));
            this.BookBtn.IdleBorderRadius = 1;
            this.BookBtn.IdleBorderThickness = 1;
            this.BookBtn.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(43)))), ((int)(((byte)(72)))));
            this.BookBtn.IdleIconLeftImage = global::InterfaceErgonomico.Properties.Resources.idea_500px;
            this.BookBtn.IdleIconRightImage = null;
            this.BookBtn.IndicateFocus = false;
            this.BookBtn.Location = new System.Drawing.Point(0, 493);
            this.BookBtn.Name = "BookBtn";
            this.BookBtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BookBtn.OnDisabledState.BorderRadius = 1;
            this.BookBtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BookBtn.OnDisabledState.BorderThickness = 1;
            this.BookBtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BookBtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BookBtn.OnDisabledState.IconLeftImage = null;
            this.BookBtn.OnDisabledState.IconRightImage = null;
            this.BookBtn.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(29)))), ((int)(((byte)(31)))), ((int)(((byte)(56)))));
            this.BookBtn.onHoverState.BorderRadius = 1;
            this.BookBtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BookBtn.onHoverState.BorderThickness = 1;
            this.BookBtn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(29)))), ((int)(((byte)(31)))), ((int)(((byte)(56)))));
            this.BookBtn.onHoverState.ForeColor = System.Drawing.Color.White;
            this.BookBtn.onHoverState.IconLeftImage = null;
            this.BookBtn.onHoverState.IconRightImage = null;
            this.BookBtn.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(43)))), ((int)(((byte)(72)))));
            this.BookBtn.OnIdleState.BorderRadius = 1;
            this.BookBtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BookBtn.OnIdleState.BorderThickness = 1;
            this.BookBtn.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(43)))), ((int)(((byte)(72)))));
            this.BookBtn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.BookBtn.OnIdleState.IconLeftImage = global::InterfaceErgonomico.Properties.Resources.idea_500px;
            this.BookBtn.OnIdleState.IconRightImage = null;
            this.BookBtn.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(43)))), ((int)(((byte)(72)))));
            this.BookBtn.OnPressedState.BorderRadius = 1;
            this.BookBtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BookBtn.OnPressedState.BorderThickness = 1;
            this.BookBtn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(43)))), ((int)(((byte)(72)))));
            this.BookBtn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.BookBtn.OnPressedState.IconLeftImage = null;
            this.BookBtn.OnPressedState.IconRightImage = null;
            this.BookBtn.Size = new System.Drawing.Size(247, 48);
            this.BookBtn.TabIndex = 3;
            this.BookBtn.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.BookBtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.BookBtn.TextMarginLeft = 0;
            this.BookBtn.TextPadding = new System.Windows.Forms.Padding(60, 0, 0, 0);
            this.BookBtn.UseDefaultRadiusAndThickness = true;
            // 
            // AboutBtn
            // 
            this.AboutBtn.AllowAnimations = true;
            this.AboutBtn.AllowMouseEffects = true;
            this.AboutBtn.AllowToggling = false;
            this.AboutBtn.AnimationSpeed = 200;
            this.AboutBtn.AutoGenerateColors = false;
            this.AboutBtn.AutoRoundBorders = false;
            this.AboutBtn.AutoSizeLeftIcon = true;
            this.AboutBtn.AutoSizeRightIcon = true;
            this.AboutBtn.BackColor = System.Drawing.Color.Transparent;
            this.AboutBtn.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(43)))), ((int)(((byte)(72)))));
            this.AboutBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("AboutBtn.BackgroundImage")));
            this.AboutBtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AboutBtn.ButtonText = "Sobre";
            this.AboutBtn.ButtonTextMarginLeft = 0;
            this.AboutBtn.ColorContrastOnClick = 45;
            this.AboutBtn.ColorContrastOnHover = 45;
            this.AboutBtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges23.BottomLeft = true;
            borderEdges23.BottomRight = true;
            borderEdges23.TopLeft = true;
            borderEdges23.TopRight = true;
            this.AboutBtn.CustomizableEdges = borderEdges23;
            this.AboutBtn.DialogResult = System.Windows.Forms.DialogResult.Cancel;
            this.AboutBtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.AboutBtn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AboutBtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.AboutBtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.AboutBtn.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.AboutBtn.ForeColor = System.Drawing.Color.White;
            this.AboutBtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.AboutBtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.AboutBtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.AboutBtn.IconMarginLeft = 11;
            this.AboutBtn.IconPadding = 5;
            this.AboutBtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.AboutBtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.AboutBtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.AboutBtn.IconSize = 25;
            this.AboutBtn.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(43)))), ((int)(((byte)(72)))));
            this.AboutBtn.IdleBorderRadius = 1;
            this.AboutBtn.IdleBorderThickness = 1;
            this.AboutBtn.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(43)))), ((int)(((byte)(72)))));
            this.AboutBtn.IdleIconLeftImage = global::InterfaceErgonomico.Properties.Resources.info_500px;
            this.AboutBtn.IdleIconRightImage = null;
            this.AboutBtn.IndicateFocus = false;
            this.AboutBtn.Location = new System.Drawing.Point(0, 439);
            this.AboutBtn.Name = "AboutBtn";
            this.AboutBtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.AboutBtn.OnDisabledState.BorderRadius = 1;
            this.AboutBtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AboutBtn.OnDisabledState.BorderThickness = 1;
            this.AboutBtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AboutBtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.AboutBtn.OnDisabledState.IconLeftImage = null;
            this.AboutBtn.OnDisabledState.IconRightImage = null;
            this.AboutBtn.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(29)))), ((int)(((byte)(31)))), ((int)(((byte)(56)))));
            this.AboutBtn.onHoverState.BorderRadius = 1;
            this.AboutBtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AboutBtn.onHoverState.BorderThickness = 1;
            this.AboutBtn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(29)))), ((int)(((byte)(31)))), ((int)(((byte)(56)))));
            this.AboutBtn.onHoverState.ForeColor = System.Drawing.Color.White;
            this.AboutBtn.onHoverState.IconLeftImage = null;
            this.AboutBtn.onHoverState.IconRightImage = null;
            this.AboutBtn.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(43)))), ((int)(((byte)(72)))));
            this.AboutBtn.OnIdleState.BorderRadius = 1;
            this.AboutBtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AboutBtn.OnIdleState.BorderThickness = 1;
            this.AboutBtn.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(43)))), ((int)(((byte)(72)))));
            this.AboutBtn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.AboutBtn.OnIdleState.IconLeftImage = global::InterfaceErgonomico.Properties.Resources.info_500px;
            this.AboutBtn.OnIdleState.IconRightImage = null;
            this.AboutBtn.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(43)))), ((int)(((byte)(72)))));
            this.AboutBtn.OnPressedState.BorderRadius = 1;
            this.AboutBtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AboutBtn.OnPressedState.BorderThickness = 1;
            this.AboutBtn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(43)))), ((int)(((byte)(72)))));
            this.AboutBtn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.AboutBtn.OnPressedState.IconLeftImage = null;
            this.AboutBtn.OnPressedState.IconRightImage = null;
            this.AboutBtn.Size = new System.Drawing.Size(247, 48);
            this.AboutBtn.TabIndex = 3;
            this.AboutBtn.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.AboutBtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.AboutBtn.TextMarginLeft = 0;
            this.AboutBtn.TextPadding = new System.Windows.Forms.Padding(60, 0, 0, 0);
            this.AboutBtn.UseDefaultRadiusAndThickness = true;
            // 
            // DashboardBtn
            // 
            this.DashboardBtn.AllowAnimations = true;
            this.DashboardBtn.AllowMouseEffects = true;
            this.DashboardBtn.AllowToggling = false;
            this.DashboardBtn.AnimationSpeed = 200;
            this.DashboardBtn.AutoGenerateColors = false;
            this.DashboardBtn.AutoRoundBorders = false;
            this.DashboardBtn.AutoSizeLeftIcon = true;
            this.DashboardBtn.AutoSizeRightIcon = true;
            this.DashboardBtn.BackColor = System.Drawing.Color.Transparent;
            this.DashboardBtn.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(43)))), ((int)(((byte)(72)))));
            this.DashboardBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("DashboardBtn.BackgroundImage")));
            this.DashboardBtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.DashboardBtn.ButtonText = "Gráficos";
            this.DashboardBtn.ButtonTextMarginLeft = 0;
            this.DashboardBtn.ColorContrastOnClick = 45;
            this.DashboardBtn.ColorContrastOnHover = 45;
            this.DashboardBtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges24.BottomLeft = true;
            borderEdges24.BottomRight = true;
            borderEdges24.TopLeft = true;
            borderEdges24.TopRight = true;
            this.DashboardBtn.CustomizableEdges = borderEdges24;
            this.DashboardBtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.DashboardBtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.DashboardBtn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.DashboardBtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.DashboardBtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.DashboardBtn.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.DashboardBtn.ForeColor = System.Drawing.Color.White;
            this.DashboardBtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.DashboardBtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.DashboardBtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.DashboardBtn.IconMarginLeft = 11;
            this.DashboardBtn.IconPadding = 5;
            this.DashboardBtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.DashboardBtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.DashboardBtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.DashboardBtn.IconSize = 25;
            this.DashboardBtn.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(43)))), ((int)(((byte)(72)))));
            this.DashboardBtn.IdleBorderRadius = 1;
            this.DashboardBtn.IdleBorderThickness = 1;
            this.DashboardBtn.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(43)))), ((int)(((byte)(72)))));
            this.DashboardBtn.IdleIconLeftImage = global::InterfaceErgonomico.Properties.Resources.google_docs_480px;
            this.DashboardBtn.IdleIconRightImage = null;
            this.DashboardBtn.IndicateFocus = false;
            this.DashboardBtn.Location = new System.Drawing.Point(0, 358);
            this.DashboardBtn.Name = "DashboardBtn";
            this.DashboardBtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.DashboardBtn.OnDisabledState.BorderRadius = 1;
            this.DashboardBtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.DashboardBtn.OnDisabledState.BorderThickness = 1;
            this.DashboardBtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.DashboardBtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.DashboardBtn.OnDisabledState.IconLeftImage = null;
            this.DashboardBtn.OnDisabledState.IconRightImage = null;
            this.DashboardBtn.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(29)))), ((int)(((byte)(31)))), ((int)(((byte)(56)))));
            this.DashboardBtn.onHoverState.BorderRadius = 1;
            this.DashboardBtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.DashboardBtn.onHoverState.BorderThickness = 1;
            this.DashboardBtn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(29)))), ((int)(((byte)(31)))), ((int)(((byte)(56)))));
            this.DashboardBtn.onHoverState.ForeColor = System.Drawing.Color.White;
            this.DashboardBtn.onHoverState.IconLeftImage = null;
            this.DashboardBtn.onHoverState.IconRightImage = null;
            this.DashboardBtn.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(43)))), ((int)(((byte)(72)))));
            this.DashboardBtn.OnIdleState.BorderRadius = 1;
            this.DashboardBtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.DashboardBtn.OnIdleState.BorderThickness = 1;
            this.DashboardBtn.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(43)))), ((int)(((byte)(72)))));
            this.DashboardBtn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.DashboardBtn.OnIdleState.IconLeftImage = global::InterfaceErgonomico.Properties.Resources.google_docs_480px;
            this.DashboardBtn.OnIdleState.IconRightImage = null;
            this.DashboardBtn.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(43)))), ((int)(((byte)(72)))));
            this.DashboardBtn.OnPressedState.BorderRadius = 1;
            this.DashboardBtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.DashboardBtn.OnPressedState.BorderThickness = 1;
            this.DashboardBtn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(43)))), ((int)(((byte)(72)))));
            this.DashboardBtn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.DashboardBtn.OnPressedState.IconLeftImage = null;
            this.DashboardBtn.OnPressedState.IconRightImage = null;
            this.DashboardBtn.Size = new System.Drawing.Size(247, 48);
            this.DashboardBtn.TabIndex = 4;
            this.DashboardBtn.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.DashboardBtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.DashboardBtn.TextMarginLeft = 0;
            this.DashboardBtn.TextPadding = new System.Windows.Forms.Padding(60, 0, 0, 0);
            this.DashboardBtn.UseDefaultRadiusAndThickness = true;
            // 
            // TimeBtn
            // 
            this.TimeBtn.AllowAnimations = true;
            this.TimeBtn.AllowMouseEffects = true;
            this.TimeBtn.AllowToggling = false;
            this.TimeBtn.AnimationSpeed = 200;
            this.TimeBtn.AutoGenerateColors = false;
            this.TimeBtn.AutoRoundBorders = false;
            this.TimeBtn.AutoSizeLeftIcon = true;
            this.TimeBtn.AutoSizeRightIcon = true;
            this.TimeBtn.BackColor = System.Drawing.Color.Transparent;
            this.TimeBtn.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(43)))), ((int)(((byte)(72)))));
            this.TimeBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("TimeBtn.BackgroundImage")));
            this.TimeBtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.TimeBtn.ButtonText = "Tempo";
            this.TimeBtn.ButtonTextMarginLeft = 0;
            this.TimeBtn.ColorContrastOnClick = 45;
            this.TimeBtn.ColorContrastOnHover = 45;
            this.TimeBtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges25.BottomLeft = true;
            borderEdges25.BottomRight = true;
            borderEdges25.TopLeft = true;
            borderEdges25.TopRight = true;
            this.TimeBtn.CustomizableEdges = borderEdges25;
            this.TimeBtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.TimeBtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.TimeBtn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.TimeBtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.TimeBtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.TimeBtn.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.TimeBtn.ForeColor = System.Drawing.Color.White;
            this.TimeBtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.TimeBtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.TimeBtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.TimeBtn.IconMarginLeft = 11;
            this.TimeBtn.IconPadding = 5;
            this.TimeBtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.TimeBtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.TimeBtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.TimeBtn.IconSize = 25;
            this.TimeBtn.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(43)))), ((int)(((byte)(72)))));
            this.TimeBtn.IdleBorderRadius = 1;
            this.TimeBtn.IdleBorderThickness = 1;
            this.TimeBtn.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(43)))), ((int)(((byte)(72)))));
            this.TimeBtn.IdleIconLeftImage = global::InterfaceErgonomico.Properties.Resources._3484174;
            this.TimeBtn.IdleIconRightImage = null;
            this.TimeBtn.IndicateFocus = false;
            this.TimeBtn.Location = new System.Drawing.Point(0, 304);
            this.TimeBtn.Name = "TimeBtn";
            this.TimeBtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.TimeBtn.OnDisabledState.BorderRadius = 1;
            this.TimeBtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.TimeBtn.OnDisabledState.BorderThickness = 1;
            this.TimeBtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.TimeBtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.TimeBtn.OnDisabledState.IconLeftImage = null;
            this.TimeBtn.OnDisabledState.IconRightImage = null;
            this.TimeBtn.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(29)))), ((int)(((byte)(31)))), ((int)(((byte)(56)))));
            this.TimeBtn.onHoverState.BorderRadius = 1;
            this.TimeBtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.TimeBtn.onHoverState.BorderThickness = 1;
            this.TimeBtn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(29)))), ((int)(((byte)(31)))), ((int)(((byte)(56)))));
            this.TimeBtn.onHoverState.ForeColor = System.Drawing.Color.White;
            this.TimeBtn.onHoverState.IconLeftImage = null;
            this.TimeBtn.onHoverState.IconRightImage = null;
            this.TimeBtn.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(43)))), ((int)(((byte)(72)))));
            this.TimeBtn.OnIdleState.BorderRadius = 1;
            this.TimeBtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.TimeBtn.OnIdleState.BorderThickness = 1;
            this.TimeBtn.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(43)))), ((int)(((byte)(72)))));
            this.TimeBtn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.TimeBtn.OnIdleState.IconLeftImage = global::InterfaceErgonomico.Properties.Resources._3484174;
            this.TimeBtn.OnIdleState.IconRightImage = null;
            this.TimeBtn.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(43)))), ((int)(((byte)(72)))));
            this.TimeBtn.OnPressedState.BorderRadius = 1;
            this.TimeBtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.TimeBtn.OnPressedState.BorderThickness = 1;
            this.TimeBtn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(43)))), ((int)(((byte)(72)))));
            this.TimeBtn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.TimeBtn.OnPressedState.IconLeftImage = null;
            this.TimeBtn.OnPressedState.IconRightImage = null;
            this.TimeBtn.Size = new System.Drawing.Size(247, 48);
            this.TimeBtn.TabIndex = 3;
            this.TimeBtn.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.TimeBtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.TimeBtn.TextMarginLeft = 0;
            this.TimeBtn.TextPadding = new System.Windows.Forms.Padding(60, 0, 0, 0);
            this.TimeBtn.UseDefaultRadiusAndThickness = true;
            // 
            // LiquidBtn
            // 
            this.LiquidBtn.AllowAnimations = true;
            this.LiquidBtn.AllowMouseEffects = true;
            this.LiquidBtn.AllowToggling = false;
            this.LiquidBtn.AnimationSpeed = 200;
            this.LiquidBtn.AutoGenerateColors = false;
            this.LiquidBtn.AutoRoundBorders = false;
            this.LiquidBtn.AutoSizeLeftIcon = true;
            this.LiquidBtn.AutoSizeRightIcon = true;
            this.LiquidBtn.BackColor = System.Drawing.Color.Transparent;
            this.LiquidBtn.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(43)))), ((int)(((byte)(72)))));
            this.LiquidBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("LiquidBtn.BackgroundImage")));
            this.LiquidBtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.LiquidBtn.ButtonText = "Hidratação";
            this.LiquidBtn.ButtonTextMarginLeft = 0;
            this.LiquidBtn.ColorContrastOnClick = 45;
            this.LiquidBtn.ColorContrastOnHover = 45;
            this.LiquidBtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges26.BottomLeft = true;
            borderEdges26.BottomRight = true;
            borderEdges26.TopLeft = true;
            borderEdges26.TopRight = true;
            this.LiquidBtn.CustomizableEdges = borderEdges26;
            this.LiquidBtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.LiquidBtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.LiquidBtn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.LiquidBtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.LiquidBtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.LiquidBtn.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.LiquidBtn.ForeColor = System.Drawing.Color.White;
            this.LiquidBtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.LiquidBtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.LiquidBtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.LiquidBtn.IconMarginLeft = 11;
            this.LiquidBtn.IconPadding = 5;
            this.LiquidBtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.LiquidBtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.LiquidBtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.LiquidBtn.IconSize = 25;
            this.LiquidBtn.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(43)))), ((int)(((byte)(72)))));
            this.LiquidBtn.IdleBorderRadius = 1;
            this.LiquidBtn.IdleBorderThickness = 1;
            this.LiquidBtn.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(43)))), ((int)(((byte)(72)))));
            this.LiquidBtn.IdleIconLeftImage = global::InterfaceErgonomico.Properties.Resources.rainmeter_512px;
            this.LiquidBtn.IdleIconRightImage = null;
            this.LiquidBtn.IndicateFocus = false;
            this.LiquidBtn.Location = new System.Drawing.Point(0, 250);
            this.LiquidBtn.Name = "LiquidBtn";
            this.LiquidBtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.LiquidBtn.OnDisabledState.BorderRadius = 1;
            this.LiquidBtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.LiquidBtn.OnDisabledState.BorderThickness = 1;
            this.LiquidBtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.LiquidBtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.LiquidBtn.OnDisabledState.IconLeftImage = null;
            this.LiquidBtn.OnDisabledState.IconRightImage = null;
            this.LiquidBtn.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(29)))), ((int)(((byte)(31)))), ((int)(((byte)(56)))));
            this.LiquidBtn.onHoverState.BorderRadius = 1;
            this.LiquidBtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.LiquidBtn.onHoverState.BorderThickness = 1;
            this.LiquidBtn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(29)))), ((int)(((byte)(31)))), ((int)(((byte)(56)))));
            this.LiquidBtn.onHoverState.ForeColor = System.Drawing.Color.White;
            this.LiquidBtn.onHoverState.IconLeftImage = null;
            this.LiquidBtn.onHoverState.IconRightImage = null;
            this.LiquidBtn.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(43)))), ((int)(((byte)(72)))));
            this.LiquidBtn.OnIdleState.BorderRadius = 1;
            this.LiquidBtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.LiquidBtn.OnIdleState.BorderThickness = 1;
            this.LiquidBtn.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(43)))), ((int)(((byte)(72)))));
            this.LiquidBtn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.LiquidBtn.OnIdleState.IconLeftImage = global::InterfaceErgonomico.Properties.Resources.rainmeter_512px;
            this.LiquidBtn.OnIdleState.IconRightImage = null;
            this.LiquidBtn.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(43)))), ((int)(((byte)(72)))));
            this.LiquidBtn.OnPressedState.BorderRadius = 1;
            this.LiquidBtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.LiquidBtn.OnPressedState.BorderThickness = 1;
            this.LiquidBtn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(43)))), ((int)(((byte)(72)))));
            this.LiquidBtn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.LiquidBtn.OnPressedState.IconLeftImage = null;
            this.LiquidBtn.OnPressedState.IconRightImage = null;
            this.LiquidBtn.Size = new System.Drawing.Size(247, 48);
            this.LiquidBtn.TabIndex = 3;
            this.LiquidBtn.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.LiquidBtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.LiquidBtn.TextMarginLeft = 0;
            this.LiquidBtn.TextPadding = new System.Windows.Forms.Padding(60, 0, 0, 0);
            this.LiquidBtn.UseDefaultRadiusAndThickness = true;
            // 
            // ErgoBtn
            // 
            this.ErgoBtn.AllowAnimations = true;
            this.ErgoBtn.AllowMouseEffects = true;
            this.ErgoBtn.AllowToggling = false;
            this.ErgoBtn.AnimationSpeed = 200;
            this.ErgoBtn.AutoGenerateColors = false;
            this.ErgoBtn.AutoRoundBorders = false;
            this.ErgoBtn.AutoSizeLeftIcon = true;
            this.ErgoBtn.AutoSizeRightIcon = true;
            this.ErgoBtn.BackColor = System.Drawing.Color.Transparent;
            this.ErgoBtn.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(43)))), ((int)(((byte)(72)))));
            this.ErgoBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("ErgoBtn.BackgroundImage")));
            this.ErgoBtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.ErgoBtn.ButtonText = "Ergonomia";
            this.ErgoBtn.ButtonTextMarginLeft = 0;
            this.ErgoBtn.ColorContrastOnClick = 45;
            this.ErgoBtn.ColorContrastOnHover = 45;
            this.ErgoBtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges27.BottomLeft = true;
            borderEdges27.BottomRight = true;
            borderEdges27.TopLeft = true;
            borderEdges27.TopRight = true;
            this.ErgoBtn.CustomizableEdges = borderEdges27;
            this.ErgoBtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.ErgoBtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.ErgoBtn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.ErgoBtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.ErgoBtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.ErgoBtn.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.ErgoBtn.ForeColor = System.Drawing.Color.White;
            this.ErgoBtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.ErgoBtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.ErgoBtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.ErgoBtn.IconMarginLeft = 11;
            this.ErgoBtn.IconPadding = 5;
            this.ErgoBtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.ErgoBtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.ErgoBtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.ErgoBtn.IconSize = 25;
            this.ErgoBtn.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(43)))), ((int)(((byte)(72)))));
            this.ErgoBtn.IdleBorderRadius = 1;
            this.ErgoBtn.IdleBorderThickness = 1;
            this.ErgoBtn.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(43)))), ((int)(((byte)(72)))));
            this.ErgoBtn.IdleIconLeftImage = global::InterfaceErgonomico.Properties.Resources.contacts_500px;
            this.ErgoBtn.IdleIconRightImage = null;
            this.ErgoBtn.IndicateFocus = false;
            this.ErgoBtn.Location = new System.Drawing.Point(0, 196);
            this.ErgoBtn.Name = "ErgoBtn";
            this.ErgoBtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.ErgoBtn.OnDisabledState.BorderRadius = 1;
            this.ErgoBtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.ErgoBtn.OnDisabledState.BorderThickness = 1;
            this.ErgoBtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.ErgoBtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.ErgoBtn.OnDisabledState.IconLeftImage = null;
            this.ErgoBtn.OnDisabledState.IconRightImage = null;
            this.ErgoBtn.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(29)))), ((int)(((byte)(31)))), ((int)(((byte)(56)))));
            this.ErgoBtn.onHoverState.BorderRadius = 1;
            this.ErgoBtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.ErgoBtn.onHoverState.BorderThickness = 1;
            this.ErgoBtn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(29)))), ((int)(((byte)(31)))), ((int)(((byte)(56)))));
            this.ErgoBtn.onHoverState.ForeColor = System.Drawing.Color.White;
            this.ErgoBtn.onHoverState.IconLeftImage = null;
            this.ErgoBtn.onHoverState.IconRightImage = null;
            this.ErgoBtn.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(43)))), ((int)(((byte)(72)))));
            this.ErgoBtn.OnIdleState.BorderRadius = 1;
            this.ErgoBtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.ErgoBtn.OnIdleState.BorderThickness = 1;
            this.ErgoBtn.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(43)))), ((int)(((byte)(72)))));
            this.ErgoBtn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.ErgoBtn.OnIdleState.IconLeftImage = global::InterfaceErgonomico.Properties.Resources.contacts_500px;
            this.ErgoBtn.OnIdleState.IconRightImage = null;
            this.ErgoBtn.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(43)))), ((int)(((byte)(72)))));
            this.ErgoBtn.OnPressedState.BorderRadius = 1;
            this.ErgoBtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.ErgoBtn.OnPressedState.BorderThickness = 1;
            this.ErgoBtn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(43)))), ((int)(((byte)(72)))));
            this.ErgoBtn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.ErgoBtn.OnPressedState.IconLeftImage = null;
            this.ErgoBtn.OnPressedState.IconRightImage = null;
            this.ErgoBtn.Size = new System.Drawing.Size(247, 48);
            this.ErgoBtn.TabIndex = 1;
            this.ErgoBtn.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.ErgoBtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.ErgoBtn.TextMarginLeft = 0;
            this.ErgoBtn.TextPadding = new System.Windows.Forms.Padding(60, 0, 0, 0);
            this.ErgoBtn.UseDefaultRadiusAndThickness = true;
            // 
            // ConfigBtn
            // 
            this.ConfigBtn.AllowAnimations = true;
            this.ConfigBtn.AllowMouseEffects = true;
            this.ConfigBtn.AllowToggling = false;
            this.ConfigBtn.AnimationSpeed = 200;
            this.ConfigBtn.AutoGenerateColors = false;
            this.ConfigBtn.AutoRoundBorders = false;
            this.ConfigBtn.AutoSizeLeftIcon = true;
            this.ConfigBtn.AutoSizeRightIcon = true;
            this.ConfigBtn.BackColor = System.Drawing.Color.Transparent;
            this.ConfigBtn.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(43)))), ((int)(((byte)(72)))));
            this.ConfigBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("ConfigBtn.BackgroundImage")));
            this.ConfigBtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.ConfigBtn.ButtonText = "Configurações";
            this.ConfigBtn.ButtonTextMarginLeft = 0;
            this.ConfigBtn.ColorContrastOnClick = 45;
            this.ConfigBtn.ColorContrastOnHover = 45;
            this.ConfigBtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges28.BottomLeft = true;
            borderEdges28.BottomRight = true;
            borderEdges28.TopLeft = true;
            borderEdges28.TopRight = true;
            this.ConfigBtn.CustomizableEdges = borderEdges28;
            this.ConfigBtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.ConfigBtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.ConfigBtn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.ConfigBtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.ConfigBtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.ConfigBtn.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.ConfigBtn.ForeColor = System.Drawing.Color.White;
            this.ConfigBtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.ConfigBtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.ConfigBtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.ConfigBtn.IconMarginLeft = 11;
            this.ConfigBtn.IconPadding = 5;
            this.ConfigBtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.ConfigBtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.ConfigBtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.ConfigBtn.IconSize = 25;
            this.ConfigBtn.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(43)))), ((int)(((byte)(72)))));
            this.ConfigBtn.IdleBorderRadius = 1;
            this.ConfigBtn.IdleBorderThickness = 1;
            this.ConfigBtn.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(43)))), ((int)(((byte)(72)))));
            this.ConfigBtn.IdleIconLeftImage = global::InterfaceErgonomico.Properties.Resources.settings_500px;
            this.ConfigBtn.IdleIconRightImage = null;
            this.ConfigBtn.IndicateFocus = false;
            this.ConfigBtn.Location = new System.Drawing.Point(0, 142);
            this.ConfigBtn.Name = "ConfigBtn";
            this.ConfigBtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.ConfigBtn.OnDisabledState.BorderRadius = 1;
            this.ConfigBtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.ConfigBtn.OnDisabledState.BorderThickness = 1;
            this.ConfigBtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.ConfigBtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.ConfigBtn.OnDisabledState.IconLeftImage = null;
            this.ConfigBtn.OnDisabledState.IconRightImage = null;
            this.ConfigBtn.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(29)))), ((int)(((byte)(31)))), ((int)(((byte)(56)))));
            this.ConfigBtn.onHoverState.BorderRadius = 1;
            this.ConfigBtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.ConfigBtn.onHoverState.BorderThickness = 1;
            this.ConfigBtn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(29)))), ((int)(((byte)(31)))), ((int)(((byte)(56)))));
            this.ConfigBtn.onHoverState.ForeColor = System.Drawing.Color.White;
            this.ConfigBtn.onHoverState.IconLeftImage = null;
            this.ConfigBtn.onHoverState.IconRightImage = null;
            this.ConfigBtn.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(43)))), ((int)(((byte)(72)))));
            this.ConfigBtn.OnIdleState.BorderRadius = 1;
            this.ConfigBtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.ConfigBtn.OnIdleState.BorderThickness = 1;
            this.ConfigBtn.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(43)))), ((int)(((byte)(72)))));
            this.ConfigBtn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.ConfigBtn.OnIdleState.IconLeftImage = global::InterfaceErgonomico.Properties.Resources.settings_500px;
            this.ConfigBtn.OnIdleState.IconRightImage = null;
            this.ConfigBtn.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(43)))), ((int)(((byte)(72)))));
            this.ConfigBtn.OnPressedState.BorderRadius = 1;
            this.ConfigBtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.ConfigBtn.OnPressedState.BorderThickness = 1;
            this.ConfigBtn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(43)))), ((int)(((byte)(72)))));
            this.ConfigBtn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.ConfigBtn.OnPressedState.IconLeftImage = null;
            this.ConfigBtn.OnPressedState.IconRightImage = null;
            this.ConfigBtn.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.ConfigBtn.Size = new System.Drawing.Size(247, 48);
            this.ConfigBtn.TabIndex = 1;
            this.ConfigBtn.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.ConfigBtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.ConfigBtn.TextMarginLeft = 0;
            this.ConfigBtn.TextPadding = new System.Windows.Forms.Padding(60, 0, 0, 0);
            this.ConfigBtn.UseDefaultRadiusAndThickness = true;
            // 
            // Logo
            // 
            this.Logo.AllowFocused = false;
            this.Logo.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.Logo.AutoSizeHeight = true;
            this.Logo.BorderRadius = 122;
            this.Logo.Image = ((System.Drawing.Image)(resources.GetObject("Logo.Image")));
            this.Logo.IsCircle = true;
            this.Logo.Location = new System.Drawing.Point(0, -54);
            this.Logo.Name = "Logo";
            this.Logo.Size = new System.Drawing.Size(244, 244);
            this.Logo.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.Logo.TabIndex = 0;
            this.Logo.TabStop = false;
            this.Logo.Type = Bunifu.UI.WinForms.BunifuPictureBox.Types.Circle;
            // 
            // bunifuImageButton1
            // 
            this.bunifuImageButton1.ActiveImage = null;
            this.bunifuImageButton1.AllowAnimations = true;
            this.bunifuImageButton1.AllowBuffering = false;
            this.bunifuImageButton1.AllowToggling = false;
            this.bunifuImageButton1.AllowZooming = true;
            this.bunifuImageButton1.AllowZoomingOnFocus = false;
            this.bunifuImageButton1.BackColor = System.Drawing.Color.Transparent;
            this.bunifuImageButton1.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuImageButton1.ErrorImage = ((System.Drawing.Image)(resources.GetObject("bunifuImageButton1.ErrorImage")));
            this.bunifuImageButton1.FadeWhenInactive = false;
            this.bunifuImageButton1.Flip = Bunifu.UI.WinForms.BunifuImageButton.FlipOrientation.Normal;
            this.bunifuImageButton1.ForeColor = System.Drawing.SystemColors.ActiveBorder;
            this.bunifuImageButton1.Image = ((System.Drawing.Image)(resources.GetObject("bunifuImageButton1.Image")));
            this.bunifuImageButton1.ImageActive = null;
            this.bunifuImageButton1.ImageLocation = null;
            this.bunifuImageButton1.ImageMargin = 0;
            this.bunifuImageButton1.ImageSize = new System.Drawing.Size(31, 28);
            this.bunifuImageButton1.ImageZoomSize = new System.Drawing.Size(32, 29);
            this.bunifuImageButton1.InitialImage = ((System.Drawing.Image)(resources.GetObject("bunifuImageButton1.InitialImage")));
            this.bunifuImageButton1.Location = new System.Drawing.Point(1037, 7);
            this.bunifuImageButton1.Name = "bunifuImageButton1";
            this.bunifuImageButton1.Rotation = 0;
            this.bunifuImageButton1.ShowActiveImage = true;
            this.bunifuImageButton1.ShowCursorChanges = true;
            this.bunifuImageButton1.ShowImageBorders = true;
            this.bunifuImageButton1.ShowSizeMarkers = false;
            this.bunifuImageButton1.Size = new System.Drawing.Size(32, 29);
            this.bunifuImageButton1.TabIndex = 1;
            this.bunifuImageButton1.ToolTipText = "";
            this.bunifuImageButton1.WaitOnLoad = false;
            this.bunifuImageButton1.Zoom = 0;
            this.bunifuImageButton1.ZoomSpeed = 10;
            this.bunifuImageButton1.Click += new System.EventHandler(this.bunifuImageButton1_Click_1);
            // 
            // SearchBtn
            // 
            this.SearchBtn.ActiveImage = null;
            this.SearchBtn.AllowAnimations = true;
            this.SearchBtn.AllowBuffering = false;
            this.SearchBtn.AllowToggling = false;
            this.SearchBtn.AllowZooming = true;
            this.SearchBtn.AllowZoomingOnFocus = false;
            this.SearchBtn.BackColor = System.Drawing.Color.Transparent;
            this.SearchBtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.SearchBtn.ErrorImage = ((System.Drawing.Image)(resources.GetObject("SearchBtn.ErrorImage")));
            this.SearchBtn.FadeWhenInactive = false;
            this.SearchBtn.Flip = Bunifu.UI.WinForms.BunifuImageButton.FlipOrientation.Normal;
            this.SearchBtn.ForeColor = System.Drawing.SystemColors.ActiveBorder;
            this.SearchBtn.Image = ((System.Drawing.Image)(resources.GetObject("SearchBtn.Image")));
            this.SearchBtn.ImageActive = null;
            this.SearchBtn.ImageLocation = null;
            this.SearchBtn.ImageMargin = 0;
            this.SearchBtn.ImageSize = new System.Drawing.Size(31, 28);
            this.SearchBtn.ImageZoomSize = new System.Drawing.Size(32, 29);
            this.SearchBtn.InitialImage = ((System.Drawing.Image)(resources.GetObject("SearchBtn.InitialImage")));
            this.SearchBtn.Location = new System.Drawing.Point(867, 7);
            this.SearchBtn.Name = "SearchBtn";
            this.SearchBtn.Rotation = 0;
            this.SearchBtn.ShowActiveImage = true;
            this.SearchBtn.ShowCursorChanges = true;
            this.SearchBtn.ShowImageBorders = true;
            this.SearchBtn.ShowSizeMarkers = false;
            this.SearchBtn.Size = new System.Drawing.Size(32, 29);
            this.SearchBtn.TabIndex = 2;
            this.SearchBtn.ToolTipText = "";
            this.SearchBtn.WaitOnLoad = false;
            this.SearchBtn.Zoom = 0;
            this.SearchBtn.ZoomSpeed = 10;
            // 
            // NotificationBtn
            // 
            this.NotificationBtn.ActiveImage = null;
            this.NotificationBtn.AllowAnimations = true;
            this.NotificationBtn.AllowBuffering = false;
            this.NotificationBtn.AllowToggling = false;
            this.NotificationBtn.AllowZooming = true;
            this.NotificationBtn.AllowZoomingOnFocus = false;
            this.NotificationBtn.BackColor = System.Drawing.Color.Transparent;
            this.NotificationBtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.NotificationBtn.ErrorImage = ((System.Drawing.Image)(resources.GetObject("NotificationBtn.ErrorImage")));
            this.NotificationBtn.FadeWhenInactive = false;
            this.NotificationBtn.Flip = Bunifu.UI.WinForms.BunifuImageButton.FlipOrientation.Normal;
            this.NotificationBtn.ForeColor = System.Drawing.SystemColors.ActiveBorder;
            this.NotificationBtn.Image = ((System.Drawing.Image)(resources.GetObject("NotificationBtn.Image")));
            this.NotificationBtn.ImageActive = null;
            this.NotificationBtn.ImageLocation = null;
            this.NotificationBtn.ImageMargin = 0;
            this.NotificationBtn.ImageSize = new System.Drawing.Size(31, 28);
            this.NotificationBtn.ImageZoomSize = new System.Drawing.Size(32, 29);
            this.NotificationBtn.InitialImage = ((System.Drawing.Image)(resources.GetObject("NotificationBtn.InitialImage")));
            this.NotificationBtn.Location = new System.Drawing.Point(905, 7);
            this.NotificationBtn.Name = "NotificationBtn";
            this.NotificationBtn.Rotation = 0;
            this.NotificationBtn.ShowActiveImage = true;
            this.NotificationBtn.ShowCursorChanges = true;
            this.NotificationBtn.ShowImageBorders = true;
            this.NotificationBtn.ShowSizeMarkers = false;
            this.NotificationBtn.Size = new System.Drawing.Size(32, 29);
            this.NotificationBtn.TabIndex = 3;
            this.NotificationBtn.ToolTipText = "";
            this.NotificationBtn.WaitOnLoad = false;
            this.NotificationBtn.Zoom = 0;
            this.NotificationBtn.ZoomSpeed = 10;
            // 
            // UserLogged
            // 
            this.UserLogged.AllowFocused = false;
            this.UserLogged.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.UserLogged.AutoSizeHeight = true;
            this.UserLogged.BorderRadius = 14;
            this.UserLogged.Image = ((System.Drawing.Image)(resources.GetObject("UserLogged.Image")));
            this.UserLogged.IsCircle = true;
            this.UserLogged.Location = new System.Drawing.Point(943, 7);
            this.UserLogged.Name = "UserLogged";
            this.UserLogged.Size = new System.Drawing.Size(29, 29);
            this.UserLogged.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.UserLogged.TabIndex = 4;
            this.UserLogged.TabStop = false;
            this.UserLogged.Type = Bunifu.UI.WinForms.BunifuPictureBox.Types.Circle;
            // 
            // MinimizeBtn
            // 
            this.MinimizeBtn.ActiveImage = null;
            this.MinimizeBtn.AllowAnimations = true;
            this.MinimizeBtn.AllowBuffering = false;
            this.MinimizeBtn.AllowToggling = false;
            this.MinimizeBtn.AllowZooming = true;
            this.MinimizeBtn.AllowZoomingOnFocus = false;
            this.MinimizeBtn.BackColor = System.Drawing.Color.Transparent;
            this.MinimizeBtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.MinimizeBtn.ErrorImage = ((System.Drawing.Image)(resources.GetObject("MinimizeBtn.ErrorImage")));
            this.MinimizeBtn.FadeWhenInactive = false;
            this.MinimizeBtn.Flip = Bunifu.UI.WinForms.BunifuImageButton.FlipOrientation.Normal;
            this.MinimizeBtn.ForeColor = System.Drawing.SystemColors.ActiveBorder;
            this.MinimizeBtn.Image = ((System.Drawing.Image)(resources.GetObject("MinimizeBtn.Image")));
            this.MinimizeBtn.ImageActive = null;
            this.MinimizeBtn.ImageLocation = null;
            this.MinimizeBtn.ImageMargin = 0;
            this.MinimizeBtn.ImageSize = new System.Drawing.Size(31, 28);
            this.MinimizeBtn.ImageZoomSize = new System.Drawing.Size(32, 29);
            this.MinimizeBtn.InitialImage = ((System.Drawing.Image)(resources.GetObject("MinimizeBtn.InitialImage")));
            this.MinimizeBtn.Location = new System.Drawing.Point(999, 7);
            this.MinimizeBtn.Name = "MinimizeBtn";
            this.MinimizeBtn.Rotation = 0;
            this.MinimizeBtn.ShowActiveImage = true;
            this.MinimizeBtn.ShowCursorChanges = true;
            this.MinimizeBtn.ShowImageBorders = true;
            this.MinimizeBtn.ShowSizeMarkers = false;
            this.MinimizeBtn.Size = new System.Drawing.Size(32, 29);
            this.MinimizeBtn.TabIndex = 5;
            this.MinimizeBtn.ToolTipText = "";
            this.MinimizeBtn.WaitOnLoad = false;
            this.MinimizeBtn.Zoom = 0;
            this.MinimizeBtn.ZoomSpeed = 10;
            this.MinimizeBtn.Click += new System.EventHandler(this.MinimizeBtn_Click);
            // 
            // Principal
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.AutoValidate = System.Windows.Forms.AutoValidate.Disable;
            this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(37)))), ((int)(((byte)(39)))), ((int)(((byte)(56)))));
            this.ClientSize = new System.Drawing.Size(1076, 644);
            this.Controls.Add(this.MinimizeBtn);
            this.Controls.Add(this.UserLogged);
            this.Controls.Add(this.NotificationBtn);
            this.Controls.Add(this.SearchBtn);
            this.Controls.Add(this.bunifuImageButton1);
            this.Controls.Add(this.panel1);
            this.ForeColor = System.Drawing.SystemColors.ButtonFace;
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
            this.KeyPreview = true;
            this.Name = "Principal";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Ergo";
            this.MouseDown += new System.Windows.Forms.MouseEventHandler(this.Principal_MouseDown);
            this.panel1.ResumeLayout(false);
            this.panel1.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.Logo)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.UserLogged)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.Panel panel1;
        private Bunifu.UI.WinForms.BunifuPictureBox Logo;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton ConfigBtn;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton BookBtn;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton AboutBtn;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton DashboardBtn;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton TimeBtn;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton LiquidBtn;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton ErgoBtn;
        private Bunifu.UI.WinForms.BunifuLabel PrincipalText;
        private Bunifu.UI.WinForms.BunifuLabel MoreText;
        private Bunifu.UI.WinForms.BunifuImageButton StartLogoutBtn;
        private Bunifu.UI.WinForms.BunifuImageButton LicenseBtn;
        private Bunifu.UI.WinForms.BunifuImageButton bunifuImageButton1;
        private Bunifu.UI.WinForms.BunifuImageButton SearchBtn;
        private Bunifu.UI.WinForms.BunifuImageButton NotificationBtn;
        private Bunifu.UI.WinForms.BunifuPictureBox UserLogged;
        private Bunifu.UI.WinForms.BunifuImageButton MinimizeBtn;
    }
}

